/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIHost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIHost{}

// ModelAPIHost struct for ModelAPIHost
type ModelAPIHost struct {
	AttachedVolumeIds []string `json:"attached_volume_ids,omitempty"`
	CreationTime *string `json:"creation_time,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	// Object containing information about the distro type of this host
	Distro *ModelDistroInfo `json:"distro,omitempty"`
	ExpirationTime *string `json:"expiration_time,omitempty"`
	HomeVolumeId *string `json:"home_volume_id,omitempty"`
	// Unique identifier of a specific host
	HostId *string `json:"host_id,omitempty"`
	// The instance type requested for the provider, primarily used for ec2 dynamic hosts
	HostType *string `json:"host_type,omitempty"`
	HostUrl *string `json:"host_url,omitempty"`
	InstanceTags []HostTag `json:"instance_tags,omitempty"`
	InstanceType *string `json:"instance_type,omitempty"`
	LastCommunication *string `json:"last_communication,omitempty"`
	NeedsReprovision *string `json:"needs_reprovision,omitempty"`
	NoExpiration *bool `json:"no_expiration,omitempty"`
	PersistentDnsName *string `json:"persistent_dns_name,omitempty"`
	// Contains options for spawn hosts.
	ProvisionOptions *ModelAPIProvisionOptions `json:"provision_options,omitempty"`
	Provisioned *bool `json:"provisioned,omitempty"`
	// Object containing information about the task the host is currently running
	RunningTask *ModelTaskInfo `json:"running_task,omitempty"`
	// Name of the process or user that started this host
	StartedBy *string `json:"started_by,omitempty"`
	// The current state of the host
	Status *string `json:"status,omitempty"`
	Tag *string `json:"tag,omitempty"`
	TotalIdleTime *int32 `json:"total_idle_time,omitempty"`
	// The user associated with this host. Set if this host was spawned for a specific user
	User *string `json:"user,omitempty"`
	UserHost *bool `json:"user_host,omitempty"`
	Zone *string `json:"zone,omitempty"`
}

// NewModelAPIHost instantiates a new ModelAPIHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIHost() *ModelAPIHost {
	this := ModelAPIHost{}
	return &this
}

// NewModelAPIHostWithDefaults instantiates a new ModelAPIHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIHostWithDefaults() *ModelAPIHost {
	this := ModelAPIHost{}
	return &this
}

// GetAttachedVolumeIds returns the AttachedVolumeIds field value if set, zero value otherwise.
func (o *ModelAPIHost) GetAttachedVolumeIds() []string {
	if o == nil || IsNil(o.AttachedVolumeIds) {
		var ret []string
		return ret
	}
	return o.AttachedVolumeIds
}

// GetAttachedVolumeIdsOk returns a tuple with the AttachedVolumeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetAttachedVolumeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AttachedVolumeIds) {
		return nil, false
	}
	return o.AttachedVolumeIds, true
}

// HasAttachedVolumeIds returns a boolean if a field has been set.
func (o *ModelAPIHost) HasAttachedVolumeIds() bool {
	if o != nil && !IsNil(o.AttachedVolumeIds) {
		return true
	}

	return false
}

// SetAttachedVolumeIds gets a reference to the given []string and assigns it to the AttachedVolumeIds field.
func (o *ModelAPIHost) SetAttachedVolumeIds(v []string) {
	o.AttachedVolumeIds = v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *ModelAPIHost) GetCreationTime() string {
	if o == nil || IsNil(o.CreationTime) {
		var ret string
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetCreationTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *ModelAPIHost) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given string and assigns it to the CreationTime field.
func (o *ModelAPIHost) SetCreationTime(v string) {
	o.CreationTime = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ModelAPIHost) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ModelAPIHost) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ModelAPIHost) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDistro returns the Distro field value if set, zero value otherwise.
func (o *ModelAPIHost) GetDistro() ModelDistroInfo {
	if o == nil || IsNil(o.Distro) {
		var ret ModelDistroInfo
		return ret
	}
	return *o.Distro
}

// GetDistroOk returns a tuple with the Distro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetDistroOk() (*ModelDistroInfo, bool) {
	if o == nil || IsNil(o.Distro) {
		return nil, false
	}
	return o.Distro, true
}

// HasDistro returns a boolean if a field has been set.
func (o *ModelAPIHost) HasDistro() bool {
	if o != nil && !IsNil(o.Distro) {
		return true
	}

	return false
}

// SetDistro gets a reference to the given ModelDistroInfo and assigns it to the Distro field.
func (o *ModelAPIHost) SetDistro(v ModelDistroInfo) {
	o.Distro = &v
}

// GetExpirationTime returns the ExpirationTime field value if set, zero value otherwise.
func (o *ModelAPIHost) GetExpirationTime() string {
	if o == nil || IsNil(o.ExpirationTime) {
		var ret string
		return ret
	}
	return *o.ExpirationTime
}

// GetExpirationTimeOk returns a tuple with the ExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetExpirationTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ExpirationTime) {
		return nil, false
	}
	return o.ExpirationTime, true
}

// HasExpirationTime returns a boolean if a field has been set.
func (o *ModelAPIHost) HasExpirationTime() bool {
	if o != nil && !IsNil(o.ExpirationTime) {
		return true
	}

	return false
}

// SetExpirationTime gets a reference to the given string and assigns it to the ExpirationTime field.
func (o *ModelAPIHost) SetExpirationTime(v string) {
	o.ExpirationTime = &v
}

// GetHomeVolumeId returns the HomeVolumeId field value if set, zero value otherwise.
func (o *ModelAPIHost) GetHomeVolumeId() string {
	if o == nil || IsNil(o.HomeVolumeId) {
		var ret string
		return ret
	}
	return *o.HomeVolumeId
}

// GetHomeVolumeIdOk returns a tuple with the HomeVolumeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetHomeVolumeIdOk() (*string, bool) {
	if o == nil || IsNil(o.HomeVolumeId) {
		return nil, false
	}
	return o.HomeVolumeId, true
}

// HasHomeVolumeId returns a boolean if a field has been set.
func (o *ModelAPIHost) HasHomeVolumeId() bool {
	if o != nil && !IsNil(o.HomeVolumeId) {
		return true
	}

	return false
}

// SetHomeVolumeId gets a reference to the given string and assigns it to the HomeVolumeId field.
func (o *ModelAPIHost) SetHomeVolumeId(v string) {
	o.HomeVolumeId = &v
}

// GetHostId returns the HostId field value if set, zero value otherwise.
func (o *ModelAPIHost) GetHostId() string {
	if o == nil || IsNil(o.HostId) {
		var ret string
		return ret
	}
	return *o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetHostIdOk() (*string, bool) {
	if o == nil || IsNil(o.HostId) {
		return nil, false
	}
	return o.HostId, true
}

// HasHostId returns a boolean if a field has been set.
func (o *ModelAPIHost) HasHostId() bool {
	if o != nil && !IsNil(o.HostId) {
		return true
	}

	return false
}

// SetHostId gets a reference to the given string and assigns it to the HostId field.
func (o *ModelAPIHost) SetHostId(v string) {
	o.HostId = &v
}

// GetHostType returns the HostType field value if set, zero value otherwise.
func (o *ModelAPIHost) GetHostType() string {
	if o == nil || IsNil(o.HostType) {
		var ret string
		return ret
	}
	return *o.HostType
}

// GetHostTypeOk returns a tuple with the HostType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetHostTypeOk() (*string, bool) {
	if o == nil || IsNil(o.HostType) {
		return nil, false
	}
	return o.HostType, true
}

// HasHostType returns a boolean if a field has been set.
func (o *ModelAPIHost) HasHostType() bool {
	if o != nil && !IsNil(o.HostType) {
		return true
	}

	return false
}

// SetHostType gets a reference to the given string and assigns it to the HostType field.
func (o *ModelAPIHost) SetHostType(v string) {
	o.HostType = &v
}

// GetHostUrl returns the HostUrl field value if set, zero value otherwise.
func (o *ModelAPIHost) GetHostUrl() string {
	if o == nil || IsNil(o.HostUrl) {
		var ret string
		return ret
	}
	return *o.HostUrl
}

// GetHostUrlOk returns a tuple with the HostUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetHostUrlOk() (*string, bool) {
	if o == nil || IsNil(o.HostUrl) {
		return nil, false
	}
	return o.HostUrl, true
}

// HasHostUrl returns a boolean if a field has been set.
func (o *ModelAPIHost) HasHostUrl() bool {
	if o != nil && !IsNil(o.HostUrl) {
		return true
	}

	return false
}

// SetHostUrl gets a reference to the given string and assigns it to the HostUrl field.
func (o *ModelAPIHost) SetHostUrl(v string) {
	o.HostUrl = &v
}

// GetInstanceTags returns the InstanceTags field value if set, zero value otherwise.
func (o *ModelAPIHost) GetInstanceTags() []HostTag {
	if o == nil || IsNil(o.InstanceTags) {
		var ret []HostTag
		return ret
	}
	return o.InstanceTags
}

// GetInstanceTagsOk returns a tuple with the InstanceTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetInstanceTagsOk() ([]HostTag, bool) {
	if o == nil || IsNil(o.InstanceTags) {
		return nil, false
	}
	return o.InstanceTags, true
}

// HasInstanceTags returns a boolean if a field has been set.
func (o *ModelAPIHost) HasInstanceTags() bool {
	if o != nil && !IsNil(o.InstanceTags) {
		return true
	}

	return false
}

// SetInstanceTags gets a reference to the given []HostTag and assigns it to the InstanceTags field.
func (o *ModelAPIHost) SetInstanceTags(v []HostTag) {
	o.InstanceTags = v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *ModelAPIHost) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *ModelAPIHost) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *ModelAPIHost) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetLastCommunication returns the LastCommunication field value if set, zero value otherwise.
func (o *ModelAPIHost) GetLastCommunication() string {
	if o == nil || IsNil(o.LastCommunication) {
		var ret string
		return ret
	}
	return *o.LastCommunication
}

// GetLastCommunicationOk returns a tuple with the LastCommunication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetLastCommunicationOk() (*string, bool) {
	if o == nil || IsNil(o.LastCommunication) {
		return nil, false
	}
	return o.LastCommunication, true
}

// HasLastCommunication returns a boolean if a field has been set.
func (o *ModelAPIHost) HasLastCommunication() bool {
	if o != nil && !IsNil(o.LastCommunication) {
		return true
	}

	return false
}

// SetLastCommunication gets a reference to the given string and assigns it to the LastCommunication field.
func (o *ModelAPIHost) SetLastCommunication(v string) {
	o.LastCommunication = &v
}

// GetNeedsReprovision returns the NeedsReprovision field value if set, zero value otherwise.
func (o *ModelAPIHost) GetNeedsReprovision() string {
	if o == nil || IsNil(o.NeedsReprovision) {
		var ret string
		return ret
	}
	return *o.NeedsReprovision
}

// GetNeedsReprovisionOk returns a tuple with the NeedsReprovision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetNeedsReprovisionOk() (*string, bool) {
	if o == nil || IsNil(o.NeedsReprovision) {
		return nil, false
	}
	return o.NeedsReprovision, true
}

// HasNeedsReprovision returns a boolean if a field has been set.
func (o *ModelAPIHost) HasNeedsReprovision() bool {
	if o != nil && !IsNil(o.NeedsReprovision) {
		return true
	}

	return false
}

// SetNeedsReprovision gets a reference to the given string and assigns it to the NeedsReprovision field.
func (o *ModelAPIHost) SetNeedsReprovision(v string) {
	o.NeedsReprovision = &v
}

// GetNoExpiration returns the NoExpiration field value if set, zero value otherwise.
func (o *ModelAPIHost) GetNoExpiration() bool {
	if o == nil || IsNil(o.NoExpiration) {
		var ret bool
		return ret
	}
	return *o.NoExpiration
}

// GetNoExpirationOk returns a tuple with the NoExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetNoExpirationOk() (*bool, bool) {
	if o == nil || IsNil(o.NoExpiration) {
		return nil, false
	}
	return o.NoExpiration, true
}

// HasNoExpiration returns a boolean if a field has been set.
func (o *ModelAPIHost) HasNoExpiration() bool {
	if o != nil && !IsNil(o.NoExpiration) {
		return true
	}

	return false
}

// SetNoExpiration gets a reference to the given bool and assigns it to the NoExpiration field.
func (o *ModelAPIHost) SetNoExpiration(v bool) {
	o.NoExpiration = &v
}

// GetPersistentDnsName returns the PersistentDnsName field value if set, zero value otherwise.
func (o *ModelAPIHost) GetPersistentDnsName() string {
	if o == nil || IsNil(o.PersistentDnsName) {
		var ret string
		return ret
	}
	return *o.PersistentDnsName
}

// GetPersistentDnsNameOk returns a tuple with the PersistentDnsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetPersistentDnsNameOk() (*string, bool) {
	if o == nil || IsNil(o.PersistentDnsName) {
		return nil, false
	}
	return o.PersistentDnsName, true
}

// HasPersistentDnsName returns a boolean if a field has been set.
func (o *ModelAPIHost) HasPersistentDnsName() bool {
	if o != nil && !IsNil(o.PersistentDnsName) {
		return true
	}

	return false
}

// SetPersistentDnsName gets a reference to the given string and assigns it to the PersistentDnsName field.
func (o *ModelAPIHost) SetPersistentDnsName(v string) {
	o.PersistentDnsName = &v
}

// GetProvisionOptions returns the ProvisionOptions field value if set, zero value otherwise.
func (o *ModelAPIHost) GetProvisionOptions() ModelAPIProvisionOptions {
	if o == nil || IsNil(o.ProvisionOptions) {
		var ret ModelAPIProvisionOptions
		return ret
	}
	return *o.ProvisionOptions
}

// GetProvisionOptionsOk returns a tuple with the ProvisionOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetProvisionOptionsOk() (*ModelAPIProvisionOptions, bool) {
	if o == nil || IsNil(o.ProvisionOptions) {
		return nil, false
	}
	return o.ProvisionOptions, true
}

// HasProvisionOptions returns a boolean if a field has been set.
func (o *ModelAPIHost) HasProvisionOptions() bool {
	if o != nil && !IsNil(o.ProvisionOptions) {
		return true
	}

	return false
}

// SetProvisionOptions gets a reference to the given ModelAPIProvisionOptions and assigns it to the ProvisionOptions field.
func (o *ModelAPIHost) SetProvisionOptions(v ModelAPIProvisionOptions) {
	o.ProvisionOptions = &v
}

// GetProvisioned returns the Provisioned field value if set, zero value otherwise.
func (o *ModelAPIHost) GetProvisioned() bool {
	if o == nil || IsNil(o.Provisioned) {
		var ret bool
		return ret
	}
	return *o.Provisioned
}

// GetProvisionedOk returns a tuple with the Provisioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetProvisionedOk() (*bool, bool) {
	if o == nil || IsNil(o.Provisioned) {
		return nil, false
	}
	return o.Provisioned, true
}

// HasProvisioned returns a boolean if a field has been set.
func (o *ModelAPIHost) HasProvisioned() bool {
	if o != nil && !IsNil(o.Provisioned) {
		return true
	}

	return false
}

// SetProvisioned gets a reference to the given bool and assigns it to the Provisioned field.
func (o *ModelAPIHost) SetProvisioned(v bool) {
	o.Provisioned = &v
}

// GetRunningTask returns the RunningTask field value if set, zero value otherwise.
func (o *ModelAPIHost) GetRunningTask() ModelTaskInfo {
	if o == nil || IsNil(o.RunningTask) {
		var ret ModelTaskInfo
		return ret
	}
	return *o.RunningTask
}

// GetRunningTaskOk returns a tuple with the RunningTask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetRunningTaskOk() (*ModelTaskInfo, bool) {
	if o == nil || IsNil(o.RunningTask) {
		return nil, false
	}
	return o.RunningTask, true
}

// HasRunningTask returns a boolean if a field has been set.
func (o *ModelAPIHost) HasRunningTask() bool {
	if o != nil && !IsNil(o.RunningTask) {
		return true
	}

	return false
}

// SetRunningTask gets a reference to the given ModelTaskInfo and assigns it to the RunningTask field.
func (o *ModelAPIHost) SetRunningTask(v ModelTaskInfo) {
	o.RunningTask = &v
}

// GetStartedBy returns the StartedBy field value if set, zero value otherwise.
func (o *ModelAPIHost) GetStartedBy() string {
	if o == nil || IsNil(o.StartedBy) {
		var ret string
		return ret
	}
	return *o.StartedBy
}

// GetStartedByOk returns a tuple with the StartedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetStartedByOk() (*string, bool) {
	if o == nil || IsNil(o.StartedBy) {
		return nil, false
	}
	return o.StartedBy, true
}

// HasStartedBy returns a boolean if a field has been set.
func (o *ModelAPIHost) HasStartedBy() bool {
	if o != nil && !IsNil(o.StartedBy) {
		return true
	}

	return false
}

// SetStartedBy gets a reference to the given string and assigns it to the StartedBy field.
func (o *ModelAPIHost) SetStartedBy(v string) {
	o.StartedBy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelAPIHost) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelAPIHost) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelAPIHost) SetStatus(v string) {
	o.Status = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *ModelAPIHost) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *ModelAPIHost) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *ModelAPIHost) SetTag(v string) {
	o.Tag = &v
}

// GetTotalIdleTime returns the TotalIdleTime field value if set, zero value otherwise.
func (o *ModelAPIHost) GetTotalIdleTime() int32 {
	if o == nil || IsNil(o.TotalIdleTime) {
		var ret int32
		return ret
	}
	return *o.TotalIdleTime
}

// GetTotalIdleTimeOk returns a tuple with the TotalIdleTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetTotalIdleTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalIdleTime) {
		return nil, false
	}
	return o.TotalIdleTime, true
}

// HasTotalIdleTime returns a boolean if a field has been set.
func (o *ModelAPIHost) HasTotalIdleTime() bool {
	if o != nil && !IsNil(o.TotalIdleTime) {
		return true
	}

	return false
}

// SetTotalIdleTime gets a reference to the given int32 and assigns it to the TotalIdleTime field.
func (o *ModelAPIHost) SetTotalIdleTime(v int32) {
	o.TotalIdleTime = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ModelAPIHost) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ModelAPIHost) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *ModelAPIHost) SetUser(v string) {
	o.User = &v
}

// GetUserHost returns the UserHost field value if set, zero value otherwise.
func (o *ModelAPIHost) GetUserHost() bool {
	if o == nil || IsNil(o.UserHost) {
		var ret bool
		return ret
	}
	return *o.UserHost
}

// GetUserHostOk returns a tuple with the UserHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetUserHostOk() (*bool, bool) {
	if o == nil || IsNil(o.UserHost) {
		return nil, false
	}
	return o.UserHost, true
}

// HasUserHost returns a boolean if a field has been set.
func (o *ModelAPIHost) HasUserHost() bool {
	if o != nil && !IsNil(o.UserHost) {
		return true
	}

	return false
}

// SetUserHost gets a reference to the given bool and assigns it to the UserHost field.
func (o *ModelAPIHost) SetUserHost(v bool) {
	o.UserHost = &v
}

// GetZone returns the Zone field value if set, zero value otherwise.
func (o *ModelAPIHost) GetZone() string {
	if o == nil || IsNil(o.Zone) {
		var ret string
		return ret
	}
	return *o.Zone
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIHost) GetZoneOk() (*string, bool) {
	if o == nil || IsNil(o.Zone) {
		return nil, false
	}
	return o.Zone, true
}

// HasZone returns a boolean if a field has been set.
func (o *ModelAPIHost) HasZone() bool {
	if o != nil && !IsNil(o.Zone) {
		return true
	}

	return false
}

// SetZone gets a reference to the given string and assigns it to the Zone field.
func (o *ModelAPIHost) SetZone(v string) {
	o.Zone = &v
}

func (o ModelAPIHost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIHost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AttachedVolumeIds) {
		toSerialize["attached_volume_ids"] = o.AttachedVolumeIds
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creation_time"] = o.CreationTime
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Distro) {
		toSerialize["distro"] = o.Distro
	}
	if !IsNil(o.ExpirationTime) {
		toSerialize["expiration_time"] = o.ExpirationTime
	}
	if !IsNil(o.HomeVolumeId) {
		toSerialize["home_volume_id"] = o.HomeVolumeId
	}
	if !IsNil(o.HostId) {
		toSerialize["host_id"] = o.HostId
	}
	if !IsNil(o.HostType) {
		toSerialize["host_type"] = o.HostType
	}
	if !IsNil(o.HostUrl) {
		toSerialize["host_url"] = o.HostUrl
	}
	if !IsNil(o.InstanceTags) {
		toSerialize["instance_tags"] = o.InstanceTags
	}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.LastCommunication) {
		toSerialize["last_communication"] = o.LastCommunication
	}
	if !IsNil(o.NeedsReprovision) {
		toSerialize["needs_reprovision"] = o.NeedsReprovision
	}
	if !IsNil(o.NoExpiration) {
		toSerialize["no_expiration"] = o.NoExpiration
	}
	if !IsNil(o.PersistentDnsName) {
		toSerialize["persistent_dns_name"] = o.PersistentDnsName
	}
	if !IsNil(o.ProvisionOptions) {
		toSerialize["provision_options"] = o.ProvisionOptions
	}
	if !IsNil(o.Provisioned) {
		toSerialize["provisioned"] = o.Provisioned
	}
	if !IsNil(o.RunningTask) {
		toSerialize["running_task"] = o.RunningTask
	}
	if !IsNil(o.StartedBy) {
		toSerialize["started_by"] = o.StartedBy
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.TotalIdleTime) {
		toSerialize["total_idle_time"] = o.TotalIdleTime
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.UserHost) {
		toSerialize["user_host"] = o.UserHost
	}
	if !IsNil(o.Zone) {
		toSerialize["zone"] = o.Zone
	}
	return toSerialize, nil
}

type NullableModelAPIHost struct {
	value *ModelAPIHost
	isSet bool
}

func (v NullableModelAPIHost) Get() *ModelAPIHost {
	return v.value
}

func (v *NullableModelAPIHost) Set(val *ModelAPIHost) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIHost) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIHost(val *ModelAPIHost) *NullableModelAPIHost {
	return &NullableModelAPIHost{value: val, isSet: true}
}

func (v NullableModelAPIHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


