/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIFailingCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIFailingCommand{}

// ModelAPIFailingCommand struct for ModelAPIFailingCommand
type ModelAPIFailingCommand struct {
	// FailureMetadataTags are tags associated with the failing command.
	FailureMetadataTags []string `json:"failure_metadata_tags,omitempty"`
	// FullDisplayName is the full display name of the failing command.
	FullDisplayName *string `json:"full_display_name,omitempty"`
}

// NewModelAPIFailingCommand instantiates a new ModelAPIFailingCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIFailingCommand() *ModelAPIFailingCommand {
	this := ModelAPIFailingCommand{}
	return &this
}

// NewModelAPIFailingCommandWithDefaults instantiates a new ModelAPIFailingCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIFailingCommandWithDefaults() *ModelAPIFailingCommand {
	this := ModelAPIFailingCommand{}
	return &this
}

// GetFailureMetadataTags returns the FailureMetadataTags field value if set, zero value otherwise.
func (o *ModelAPIFailingCommand) GetFailureMetadataTags() []string {
	if o == nil || IsNil(o.FailureMetadataTags) {
		var ret []string
		return ret
	}
	return o.FailureMetadataTags
}

// GetFailureMetadataTagsOk returns a tuple with the FailureMetadataTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIFailingCommand) GetFailureMetadataTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.FailureMetadataTags) {
		return nil, false
	}
	return o.FailureMetadataTags, true
}

// HasFailureMetadataTags returns a boolean if a field has been set.
func (o *ModelAPIFailingCommand) HasFailureMetadataTags() bool {
	if o != nil && !IsNil(o.FailureMetadataTags) {
		return true
	}

	return false
}

// SetFailureMetadataTags gets a reference to the given []string and assigns it to the FailureMetadataTags field.
func (o *ModelAPIFailingCommand) SetFailureMetadataTags(v []string) {
	o.FailureMetadataTags = v
}

// GetFullDisplayName returns the FullDisplayName field value if set, zero value otherwise.
func (o *ModelAPIFailingCommand) GetFullDisplayName() string {
	if o == nil || IsNil(o.FullDisplayName) {
		var ret string
		return ret
	}
	return *o.FullDisplayName
}

// GetFullDisplayNameOk returns a tuple with the FullDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIFailingCommand) GetFullDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullDisplayName) {
		return nil, false
	}
	return o.FullDisplayName, true
}

// HasFullDisplayName returns a boolean if a field has been set.
func (o *ModelAPIFailingCommand) HasFullDisplayName() bool {
	if o != nil && !IsNil(o.FullDisplayName) {
		return true
	}

	return false
}

// SetFullDisplayName gets a reference to the given string and assigns it to the FullDisplayName field.
func (o *ModelAPIFailingCommand) SetFullDisplayName(v string) {
	o.FullDisplayName = &v
}

func (o ModelAPIFailingCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIFailingCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FailureMetadataTags) {
		toSerialize["failure_metadata_tags"] = o.FailureMetadataTags
	}
	if !IsNil(o.FullDisplayName) {
		toSerialize["full_display_name"] = o.FullDisplayName
	}
	return toSerialize, nil
}

type NullableModelAPIFailingCommand struct {
	value *ModelAPIFailingCommand
	isSet bool
}

func (v NullableModelAPIFailingCommand) Get() *ModelAPIFailingCommand {
	return v.value
}

func (v *NullableModelAPIFailingCommand) Set(val *ModelAPIFailingCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIFailingCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIFailingCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIFailingCommand(val *ModelAPIFailingCommand) *NullableModelAPIFailingCommand {
	return &NullableModelAPIFailingCommand{value: val, isSet: true}
}

func (v NullableModelAPIFailingCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIFailingCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


