/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIWorkstationSetupCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIWorkstationSetupCommand{}

// ModelAPIWorkstationSetupCommand struct for ModelAPIWorkstationSetupCommand
type ModelAPIWorkstationSetupCommand struct {
	// Command to run in the workstation.
	Command *string `json:"command,omitempty"`
	// Directory where the command runs.
	Directory *string `json:"directory,omitempty"`
}

// NewModelAPIWorkstationSetupCommand instantiates a new ModelAPIWorkstationSetupCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIWorkstationSetupCommand() *ModelAPIWorkstationSetupCommand {
	this := ModelAPIWorkstationSetupCommand{}
	return &this
}

// NewModelAPIWorkstationSetupCommandWithDefaults instantiates a new ModelAPIWorkstationSetupCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIWorkstationSetupCommandWithDefaults() *ModelAPIWorkstationSetupCommand {
	this := ModelAPIWorkstationSetupCommand{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *ModelAPIWorkstationSetupCommand) GetCommand() string {
	if o == nil || IsNil(o.Command) {
		var ret string
		return ret
	}
	return *o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIWorkstationSetupCommand) GetCommandOk() (*string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *ModelAPIWorkstationSetupCommand) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given string and assigns it to the Command field.
func (o *ModelAPIWorkstationSetupCommand) SetCommand(v string) {
	o.Command = &v
}

// GetDirectory returns the Directory field value if set, zero value otherwise.
func (o *ModelAPIWorkstationSetupCommand) GetDirectory() string {
	if o == nil || IsNil(o.Directory) {
		var ret string
		return ret
	}
	return *o.Directory
}

// GetDirectoryOk returns a tuple with the Directory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIWorkstationSetupCommand) GetDirectoryOk() (*string, bool) {
	if o == nil || IsNil(o.Directory) {
		return nil, false
	}
	return o.Directory, true
}

// HasDirectory returns a boolean if a field has been set.
func (o *ModelAPIWorkstationSetupCommand) HasDirectory() bool {
	if o != nil && !IsNil(o.Directory) {
		return true
	}

	return false
}

// SetDirectory gets a reference to the given string and assigns it to the Directory field.
func (o *ModelAPIWorkstationSetupCommand) SetDirectory(v string) {
	o.Directory = &v
}

func (o ModelAPIWorkstationSetupCommand) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIWorkstationSetupCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Directory) {
		toSerialize["directory"] = o.Directory
	}
	return toSerialize, nil
}

type NullableModelAPIWorkstationSetupCommand struct {
	value *ModelAPIWorkstationSetupCommand
	isSet bool
}

func (v NullableModelAPIWorkstationSetupCommand) Get() *ModelAPIWorkstationSetupCommand {
	return v.value
}

func (v *NullableModelAPIWorkstationSetupCommand) Set(val *ModelAPIWorkstationSetupCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIWorkstationSetupCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIWorkstationSetupCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIWorkstationSetupCommand(val *ModelAPIWorkstationSetupCommand) *NullableModelAPIWorkstationSetupCommand {
	return &NullableModelAPIWorkstationSetupCommand{value: val, isSet: true}
}

func (v NullableModelAPIWorkstationSetupCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIWorkstationSetupCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


