/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIParameter{}

// ModelAPIParameter struct for ModelAPIParameter
type ModelAPIParameter struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewModelAPIParameter instantiates a new ModelAPIParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIParameter() *ModelAPIParameter {
	this := ModelAPIParameter{}
	return &this
}

// NewModelAPIParameterWithDefaults instantiates a new ModelAPIParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIParameterWithDefaults() *ModelAPIParameter {
	this := ModelAPIParameter{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ModelAPIParameter) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIParameter) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ModelAPIParameter) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ModelAPIParameter) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ModelAPIParameter) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIParameter) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ModelAPIParameter) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ModelAPIParameter) SetValue(v string) {
	o.Value = &v
}

func (o ModelAPIParameter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableModelAPIParameter struct {
	value *ModelAPIParameter
	isSet bool
}

func (v NullableModelAPIParameter) Get() *ModelAPIParameter {
	return v.value
}

func (v *NullableModelAPIParameter) Set(val *ModelAPIParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIParameter(val *ModelAPIParameter) *NullableModelAPIParameter {
	return &NullableModelAPIParameter{value: val, isSet: true}
}

func (v NullableModelAPIParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


