/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RouteOffboardUserEmail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RouteOffboardUserEmail{}

// RouteOffboardUserEmail struct for RouteOffboardUserEmail
type RouteOffboardUserEmail struct {
	// the email of the user
	Email string `json:"email"`
}

type _RouteOffboardUserEmail RouteOffboardUserEmail

// NewRouteOffboardUserEmail instantiates a new RouteOffboardUserEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouteOffboardUserEmail(email string) *RouteOffboardUserEmail {
	this := RouteOffboardUserEmail{}
	this.Email = email
	return &this
}

// NewRouteOffboardUserEmailWithDefaults instantiates a new RouteOffboardUserEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteOffboardUserEmailWithDefaults() *RouteOffboardUserEmail {
	this := RouteOffboardUserEmail{}
	return &this
}

// GetEmail returns the Email field value
func (o *RouteOffboardUserEmail) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RouteOffboardUserEmail) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RouteOffboardUserEmail) SetEmail(v string) {
	o.Email = v
}

func (o RouteOffboardUserEmail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RouteOffboardUserEmail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *RouteOffboardUserEmail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRouteOffboardUserEmail := _RouteOffboardUserEmail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRouteOffboardUserEmail)

	if err != nil {
		return err
	}

	*o = RouteOffboardUserEmail(varRouteOffboardUserEmail)

	return err
}

type NullableRouteOffboardUserEmail struct {
	value *RouteOffboardUserEmail
	isSet bool
}

func (v NullableRouteOffboardUserEmail) Get() *RouteOffboardUserEmail {
	return v.value
}

func (v *NullableRouteOffboardUserEmail) Set(val *RouteOffboardUserEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteOffboardUserEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteOffboardUserEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteOffboardUserEmail(val *RouteOffboardUserEmail) *NullableRouteOffboardUserEmail {
	return &NullableRouteOffboardUserEmail{value: val, isSet: true}
}

func (v NullableRouteOffboardUserEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteOffboardUserEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


