/*
Test Selection Services

Test Selection services, owner: DevProd Services & Integrations team

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost{}

// BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost struct for BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost
type BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost struct {
	ProjectId string `json:"project_id"`
	BuildVariantName string `json:"build_variant_name"`
}

type _BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost

// NewBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost instantiates a new BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost(projectId string, buildVariantName string) *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost {
	this := BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost{}
	this.ProjectId = projectId
	this.BuildVariantName = buildVariantName
	return &this
}

// NewBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePostWithDefaults instantiates a new BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePostWithDefaults() *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost {
	this := BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) SetProjectId(v string) {
	o.ProjectId = v
}

// GetBuildVariantName returns the BuildVariantName field value
func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) GetBuildVariantName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildVariantName
}

// GetBuildVariantNameOk returns a tuple with the BuildVariantName field value
// and a boolean to check if the value has been set.
func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) GetBuildVariantNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildVariantName, true
}

// SetBuildVariantName sets field value
func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) SetBuildVariantName(v string) {
	o.BuildVariantName = v
}

func (o BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["build_variant_name"] = o.BuildVariantName
	return toSerialize, nil
}

func (o *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"build_variant_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost := _BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost)

	if err != nil {
		return err
	}

	*o = BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost(varBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost)

	return err
}

type NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost struct {
	value *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost
	isSet bool
}

func (v NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) Get() *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost {
	return v.value
}

func (v *NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) Set(val *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost(val *BodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) *NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost {
	return &NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost{value: val, isSet: true}
}

func (v NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyGetVariantStateDataInBodyApiTestSelectionGetVariantStatePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


