/*
Test Selection Services

Test Selection services, owner: DevProd Services & Integrations team

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StrategyTestMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategyTestMetrics{}

// StrategyTestMetrics Metrics for a specific test evaluated by a strategy.
type StrategyTestMetrics struct {
	TestName string `json:"test_name"`
	WasFiltered bool `json:"was_filtered"`
	StrategyName StrategyEnum `json:"strategy_name"`
	ExpectedOutcome string `json:"expected_outcome"`
	Explanation string `json:"explanation"`
	BaselineResult NullableTestResult `json:"baseline_result,omitempty"`
	StrategyResult NullableTestResult `json:"strategy_result,omitempty"`
	SubsequentResult NullableTestResult `json:"subsequent_result,omitempty"`
	Classification TestClassification `json:"classification"`
	KnownIssues []KnownIssue `json:"known_issues,omitempty"`
	IsKnownIssue bool `json:"is_known_issue"`
}

type _StrategyTestMetrics StrategyTestMetrics

// NewStrategyTestMetrics instantiates a new StrategyTestMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategyTestMetrics(testName string, wasFiltered bool, strategyName StrategyEnum, expectedOutcome string, explanation string, classification TestClassification, isKnownIssue bool) *StrategyTestMetrics {
	this := StrategyTestMetrics{}
	this.TestName = testName
	this.WasFiltered = wasFiltered
	this.StrategyName = strategyName
	this.ExpectedOutcome = expectedOutcome
	this.Explanation = explanation
	this.Classification = classification
	this.IsKnownIssue = isKnownIssue
	return &this
}

// NewStrategyTestMetricsWithDefaults instantiates a new StrategyTestMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyTestMetricsWithDefaults() *StrategyTestMetrics {
	this := StrategyTestMetrics{}
	return &this
}

// GetTestName returns the TestName field value
func (o *StrategyTestMetrics) GetTestName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TestName
}

// GetTestNameOk returns a tuple with the TestName field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetTestNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TestName, true
}

// SetTestName sets field value
func (o *StrategyTestMetrics) SetTestName(v string) {
	o.TestName = v
}

// GetWasFiltered returns the WasFiltered field value
func (o *StrategyTestMetrics) GetWasFiltered() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WasFiltered
}

// GetWasFilteredOk returns a tuple with the WasFiltered field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetWasFilteredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WasFiltered, true
}

// SetWasFiltered sets field value
func (o *StrategyTestMetrics) SetWasFiltered(v bool) {
	o.WasFiltered = v
}

// GetStrategyName returns the StrategyName field value
func (o *StrategyTestMetrics) GetStrategyName() StrategyEnum {
	if o == nil {
		var ret StrategyEnum
		return ret
	}

	return o.StrategyName
}

// GetStrategyNameOk returns a tuple with the StrategyName field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetStrategyNameOk() (*StrategyEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StrategyName, true
}

// SetStrategyName sets field value
func (o *StrategyTestMetrics) SetStrategyName(v StrategyEnum) {
	o.StrategyName = v
}

// GetExpectedOutcome returns the ExpectedOutcome field value
func (o *StrategyTestMetrics) GetExpectedOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedOutcome
}

// GetExpectedOutcomeOk returns a tuple with the ExpectedOutcome field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetExpectedOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedOutcome, true
}

// SetExpectedOutcome sets field value
func (o *StrategyTestMetrics) SetExpectedOutcome(v string) {
	o.ExpectedOutcome = v
}

// GetExplanation returns the Explanation field value
func (o *StrategyTestMetrics) GetExplanation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Explanation
}

// GetExplanationOk returns a tuple with the Explanation field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetExplanationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Explanation, true
}

// SetExplanation sets field value
func (o *StrategyTestMetrics) SetExplanation(v string) {
	o.Explanation = v
}

// GetBaselineResult returns the BaselineResult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StrategyTestMetrics) GetBaselineResult() TestResult {
	if o == nil || IsNil(o.BaselineResult.Get()) {
		var ret TestResult
		return ret
	}
	return *o.BaselineResult.Get()
}

// GetBaselineResultOk returns a tuple with the BaselineResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrategyTestMetrics) GetBaselineResultOk() (*TestResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaselineResult.Get(), o.BaselineResult.IsSet()
}

// HasBaselineResult returns a boolean if a field has been set.
func (o *StrategyTestMetrics) HasBaselineResult() bool {
	if o != nil && o.BaselineResult.IsSet() {
		return true
	}

	return false
}

// SetBaselineResult gets a reference to the given NullableTestResult and assigns it to the BaselineResult field.
func (o *StrategyTestMetrics) SetBaselineResult(v TestResult) {
	o.BaselineResult.Set(&v)
}
// SetBaselineResultNil sets the value for BaselineResult to be an explicit nil
func (o *StrategyTestMetrics) SetBaselineResultNil() {
	o.BaselineResult.Set(nil)
}

// UnsetBaselineResult ensures that no value is present for BaselineResult, not even an explicit nil
func (o *StrategyTestMetrics) UnsetBaselineResult() {
	o.BaselineResult.Unset()
}

// GetStrategyResult returns the StrategyResult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StrategyTestMetrics) GetStrategyResult() TestResult {
	if o == nil || IsNil(o.StrategyResult.Get()) {
		var ret TestResult
		return ret
	}
	return *o.StrategyResult.Get()
}

// GetStrategyResultOk returns a tuple with the StrategyResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrategyTestMetrics) GetStrategyResultOk() (*TestResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.StrategyResult.Get(), o.StrategyResult.IsSet()
}

// HasStrategyResult returns a boolean if a field has been set.
func (o *StrategyTestMetrics) HasStrategyResult() bool {
	if o != nil && o.StrategyResult.IsSet() {
		return true
	}

	return false
}

// SetStrategyResult gets a reference to the given NullableTestResult and assigns it to the StrategyResult field.
func (o *StrategyTestMetrics) SetStrategyResult(v TestResult) {
	o.StrategyResult.Set(&v)
}
// SetStrategyResultNil sets the value for StrategyResult to be an explicit nil
func (o *StrategyTestMetrics) SetStrategyResultNil() {
	o.StrategyResult.Set(nil)
}

// UnsetStrategyResult ensures that no value is present for StrategyResult, not even an explicit nil
func (o *StrategyTestMetrics) UnsetStrategyResult() {
	o.StrategyResult.Unset()
}

// GetSubsequentResult returns the SubsequentResult field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StrategyTestMetrics) GetSubsequentResult() TestResult {
	if o == nil || IsNil(o.SubsequentResult.Get()) {
		var ret TestResult
		return ret
	}
	return *o.SubsequentResult.Get()
}

// GetSubsequentResultOk returns a tuple with the SubsequentResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StrategyTestMetrics) GetSubsequentResultOk() (*TestResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubsequentResult.Get(), o.SubsequentResult.IsSet()
}

// HasSubsequentResult returns a boolean if a field has been set.
func (o *StrategyTestMetrics) HasSubsequentResult() bool {
	if o != nil && o.SubsequentResult.IsSet() {
		return true
	}

	return false
}

// SetSubsequentResult gets a reference to the given NullableTestResult and assigns it to the SubsequentResult field.
func (o *StrategyTestMetrics) SetSubsequentResult(v TestResult) {
	o.SubsequentResult.Set(&v)
}
// SetSubsequentResultNil sets the value for SubsequentResult to be an explicit nil
func (o *StrategyTestMetrics) SetSubsequentResultNil() {
	o.SubsequentResult.Set(nil)
}

// UnsetSubsequentResult ensures that no value is present for SubsequentResult, not even an explicit nil
func (o *StrategyTestMetrics) UnsetSubsequentResult() {
	o.SubsequentResult.Unset()
}

// GetClassification returns the Classification field value
func (o *StrategyTestMetrics) GetClassification() TestClassification {
	if o == nil {
		var ret TestClassification
		return ret
	}

	return o.Classification
}

// GetClassificationOk returns a tuple with the Classification field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetClassificationOk() (*TestClassification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Classification, true
}

// SetClassification sets field value
func (o *StrategyTestMetrics) SetClassification(v TestClassification) {
	o.Classification = v
}

// GetKnownIssues returns the KnownIssues field value if set, zero value otherwise.
func (o *StrategyTestMetrics) GetKnownIssues() []KnownIssue {
	if o == nil || IsNil(o.KnownIssues) {
		var ret []KnownIssue
		return ret
	}
	return o.KnownIssues
}

// GetKnownIssuesOk returns a tuple with the KnownIssues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetKnownIssuesOk() ([]KnownIssue, bool) {
	if o == nil || IsNil(o.KnownIssues) {
		return nil, false
	}
	return o.KnownIssues, true
}

// HasKnownIssues returns a boolean if a field has been set.
func (o *StrategyTestMetrics) HasKnownIssues() bool {
	if o != nil && !IsNil(o.KnownIssues) {
		return true
	}

	return false
}

// SetKnownIssues gets a reference to the given []KnownIssue and assigns it to the KnownIssues field.
func (o *StrategyTestMetrics) SetKnownIssues(v []KnownIssue) {
	o.KnownIssues = v
}

// GetIsKnownIssue returns the IsKnownIssue field value
func (o *StrategyTestMetrics) GetIsKnownIssue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsKnownIssue
}

// GetIsKnownIssueOk returns a tuple with the IsKnownIssue field value
// and a boolean to check if the value has been set.
func (o *StrategyTestMetrics) GetIsKnownIssueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsKnownIssue, true
}

// SetIsKnownIssue sets field value
func (o *StrategyTestMetrics) SetIsKnownIssue(v bool) {
	o.IsKnownIssue = v
}

func (o StrategyTestMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategyTestMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["test_name"] = o.TestName
	toSerialize["was_filtered"] = o.WasFiltered
	toSerialize["strategy_name"] = o.StrategyName
	toSerialize["expected_outcome"] = o.ExpectedOutcome
	toSerialize["explanation"] = o.Explanation
	if o.BaselineResult.IsSet() {
		toSerialize["baseline_result"] = o.BaselineResult.Get()
	}
	if o.StrategyResult.IsSet() {
		toSerialize["strategy_result"] = o.StrategyResult.Get()
	}
	if o.SubsequentResult.IsSet() {
		toSerialize["subsequent_result"] = o.SubsequentResult.Get()
	}
	toSerialize["classification"] = o.Classification
	if !IsNil(o.KnownIssues) {
		toSerialize["known_issues"] = o.KnownIssues
	}
	toSerialize["is_known_issue"] = o.IsKnownIssue
	return toSerialize, nil
}

func (o *StrategyTestMetrics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"test_name",
		"was_filtered",
		"strategy_name",
		"expected_outcome",
		"explanation",
		"classification",
		"is_known_issue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategyTestMetrics := _StrategyTestMetrics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStrategyTestMetrics)

	if err != nil {
		return err
	}

	*o = StrategyTestMetrics(varStrategyTestMetrics)

	return err
}

type NullableStrategyTestMetrics struct {
	value *StrategyTestMetrics
	isSet bool
}

func (v NullableStrategyTestMetrics) Get() *StrategyTestMetrics {
	return v.value
}

func (v *NullableStrategyTestMetrics) Set(val *StrategyTestMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategyTestMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategyTestMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategyTestMetrics(val *StrategyTestMetrics) *NullableStrategyTestMetrics {
	return &NullableStrategyTestMetrics{value: val, isSet: true}
}

func (v NullableStrategyTestMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategyTestMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


