/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIExpansion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIExpansion{}

// ModelAPIExpansion struct for ModelAPIExpansion
type ModelAPIExpansion struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewModelAPIExpansion instantiates a new ModelAPIExpansion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIExpansion() *ModelAPIExpansion {
	this := ModelAPIExpansion{}
	return &this
}

// NewModelAPIExpansionWithDefaults instantiates a new ModelAPIExpansion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIExpansionWithDefaults() *ModelAPIExpansion {
	this := ModelAPIExpansion{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ModelAPIExpansion) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIExpansion) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ModelAPIExpansion) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ModelAPIExpansion) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ModelAPIExpansion) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIExpansion) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ModelAPIExpansion) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ModelAPIExpansion) SetValue(v string) {
	o.Value = &v
}

func (o ModelAPIExpansion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIExpansion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableModelAPIExpansion struct {
	value *ModelAPIExpansion
	isSet bool
}

func (v NullableModelAPIExpansion) Get() *ModelAPIExpansion {
	return v.value
}

func (v *NullableModelAPIExpansion) Set(val *ModelAPIExpansion) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIExpansion) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIExpansion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIExpansion(val *ModelAPIExpansion) *NullableModelAPIExpansion {
	return &NullableModelAPIExpansion{value: val, isSet: true}
}

func (v NullableModelAPIExpansion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIExpansion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


