/*
Test Selection Services

Test Selection services, owner: DevProd Services & Integrations team

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost{}

// BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost struct for BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost
type BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost struct {
	ProjectId string `json:"project_id"`
	Requester string `json:"requester"`
	BuildVariantName string `json:"build_variant_name"`
	TaskId string `json:"task_id"`
	TaskName string `json:"task_name"`
	Strategies []StrategyEnum `json:"strategies,omitempty"`
}

type _BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost

// NewBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost instantiates a new BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost(projectId string, requester string, buildVariantName string, taskId string, taskName string) *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost {
	this := BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost{}
	this.ProjectId = projectId
	this.Requester = requester
	this.BuildVariantName = buildVariantName
	this.TaskId = taskId
	this.TaskName = taskName
	return &this
}

// NewBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPostWithDefaults instantiates a new BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPostWithDefaults() *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost {
	this := BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) SetProjectId(v string) {
	o.ProjectId = v
}

// GetRequester returns the Requester field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetRequester() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Requester
}

// GetRequesterOk returns a tuple with the Requester field value
// and a boolean to check if the value has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetRequesterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requester, true
}

// SetRequester sets field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) SetRequester(v string) {
	o.Requester = v
}

// GetBuildVariantName returns the BuildVariantName field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetBuildVariantName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildVariantName
}

// GetBuildVariantNameOk returns a tuple with the BuildVariantName field value
// and a boolean to check if the value has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetBuildVariantNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildVariantName, true
}

// SetBuildVariantName sets field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) SetBuildVariantName(v string) {
	o.BuildVariantName = v
}

// GetTaskId returns the TaskId field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) SetTaskId(v string) {
	o.TaskId = v
}

// GetTaskName returns the TaskName field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetTaskName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskName
}

// GetTaskNameOk returns a tuple with the TaskName field value
// and a boolean to check if the value has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetTaskNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskName, true
}

// SetTaskName sets field value
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) SetTaskName(v string) {
	o.TaskName = v
}

// GetStrategies returns the Strategies field value if set, zero value otherwise.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetStrategies() []StrategyEnum {
	if o == nil || IsNil(o.Strategies) {
		var ret []StrategyEnum
		return ret
	}
	return o.Strategies
}

// GetStrategiesOk returns a tuple with the Strategies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) GetStrategiesOk() ([]StrategyEnum, bool) {
	if o == nil || IsNil(o.Strategies) {
		return nil, false
	}
	return o.Strategies, true
}

// HasStrategies returns a boolean if a field has been set.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) HasStrategies() bool {
	if o != nil && !IsNil(o.Strategies) {
		return true
	}

	return false
}

// SetStrategies gets a reference to the given []StrategyEnum and assigns it to the Strategies field.
func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) SetStrategies(v []StrategyEnum) {
	o.Strategies = v
}

func (o BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["requester"] = o.Requester
	toSerialize["build_variant_name"] = o.BuildVariantName
	toSerialize["task_id"] = o.TaskId
	toSerialize["task_name"] = o.TaskName
	if !IsNil(o.Strategies) {
		toSerialize["strategies"] = o.Strategies
	}
	return toSerialize, nil
}

func (o *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"requester",
		"build_variant_name",
		"task_id",
		"task_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost := _BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost)

	if err != nil {
		return err
	}

	*o = BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost(varBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost)

	return err
}

type NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost struct {
	value *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost
	isSet bool
}

func (v NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) Get() *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost {
	return v.value
}

func (v *NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) Set(val *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost(val *BodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) *NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost {
	return &NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost{value: val, isSet: true}
}

func (v NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodySelectAllKnownTestsOfATaskWithDataInBodyApiTestSelectionSelectKnownTestsPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


