/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIExternalLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIExternalLink{}

// ModelAPIExternalLink struct for ModelAPIExternalLink
type ModelAPIExternalLink struct {
	// Display name for the URL.
	DisplayName *string `json:"display_name,omitempty"`
	// Requester filter for when to display the link.
	Requesters []string `json:"requesters,omitempty"`
	// URL format to add to the version metadata panel.
	UrlTemplate *string `json:"url_template,omitempty"`
}

// NewModelAPIExternalLink instantiates a new ModelAPIExternalLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIExternalLink() *ModelAPIExternalLink {
	this := ModelAPIExternalLink{}
	return &this
}

// NewModelAPIExternalLinkWithDefaults instantiates a new ModelAPIExternalLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIExternalLinkWithDefaults() *ModelAPIExternalLink {
	this := ModelAPIExternalLink{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ModelAPIExternalLink) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIExternalLink) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ModelAPIExternalLink) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ModelAPIExternalLink) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetRequesters returns the Requesters field value if set, zero value otherwise.
func (o *ModelAPIExternalLink) GetRequesters() []string {
	if o == nil || IsNil(o.Requesters) {
		var ret []string
		return ret
	}
	return o.Requesters
}

// GetRequestersOk returns a tuple with the Requesters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIExternalLink) GetRequestersOk() ([]string, bool) {
	if o == nil || IsNil(o.Requesters) {
		return nil, false
	}
	return o.Requesters, true
}

// HasRequesters returns a boolean if a field has been set.
func (o *ModelAPIExternalLink) HasRequesters() bool {
	if o != nil && !IsNil(o.Requesters) {
		return true
	}

	return false
}

// SetRequesters gets a reference to the given []string and assigns it to the Requesters field.
func (o *ModelAPIExternalLink) SetRequesters(v []string) {
	o.Requesters = v
}

// GetUrlTemplate returns the UrlTemplate field value if set, zero value otherwise.
func (o *ModelAPIExternalLink) GetUrlTemplate() string {
	if o == nil || IsNil(o.UrlTemplate) {
		var ret string
		return ret
	}
	return *o.UrlTemplate
}

// GetUrlTemplateOk returns a tuple with the UrlTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIExternalLink) GetUrlTemplateOk() (*string, bool) {
	if o == nil || IsNil(o.UrlTemplate) {
		return nil, false
	}
	return o.UrlTemplate, true
}

// HasUrlTemplate returns a boolean if a field has been set.
func (o *ModelAPIExternalLink) HasUrlTemplate() bool {
	if o != nil && !IsNil(o.UrlTemplate) {
		return true
	}

	return false
}

// SetUrlTemplate gets a reference to the given string and assigns it to the UrlTemplate field.
func (o *ModelAPIExternalLink) SetUrlTemplate(v string) {
	o.UrlTemplate = &v
}

func (o ModelAPIExternalLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIExternalLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Requesters) {
		toSerialize["requesters"] = o.Requesters
	}
	if !IsNil(o.UrlTemplate) {
		toSerialize["url_template"] = o.UrlTemplate
	}
	return toSerialize, nil
}

type NullableModelAPIExternalLink struct {
	value *ModelAPIExternalLink
	isSet bool
}

func (v NullableModelAPIExternalLink) Get() *ModelAPIExternalLink {
	return v.value
}

func (v *NullableModelAPIExternalLink) Set(val *ModelAPIExternalLink) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIExternalLink) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIExternalLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIExternalLink(val *ModelAPIExternalLink) *NullableModelAPIExternalLink {
	return &NullableModelAPIExternalLink{value: val, isSet: true}
}

func (v NullableModelAPIExternalLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIExternalLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


