/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIDistro type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIDistro{}

// ModelAPIDistro struct for ModelAPIDistro
type ModelAPIDistro struct {
	AdminOnly *bool `json:"admin_only,omitempty"`
	Aliases []string `json:"aliases,omitempty"`
	Arch *string `json:"arch,omitempty"`
	AuthorizedKeysFile *string `json:"authorized_keys_file,omitempty"`
	BootstrapSettings *ModelAPIBootstrapSettings `json:"bootstrap_settings,omitempty"`
	ContainerPool *string `json:"container_pool,omitempty"`
	DisableShallowClone *bool `json:"disable_shallow_clone,omitempty"`
	Disabled *bool `json:"disabled,omitempty"`
	DispatcherSettings *ModelAPIDispatcherSettings `json:"dispatcher_settings,omitempty"`
	ExecUser *string `json:"exec_user,omitempty"`
	Expansions []ModelAPIExpansion `json:"expansions,omitempty"`
	FinderSettings *ModelAPIFinderSettings `json:"finder_settings,omitempty"`
	HomeVolumeSettings *ModelAPIHomeVolumeSettings `json:"home_volume_settings,omitempty"`
	HostAllocatorSettings *ModelAPIHostAllocatorSettings `json:"host_allocator_settings,omitempty"`
	IcecreamSettings *ModelAPIIceCreamSettings `json:"icecream_settings,omitempty"`
	ImageId *string `json:"image_id,omitempty"`
	IsCluster *bool `json:"is_cluster,omitempty"`
	IsVirtualWorkstation *bool `json:"is_virtual_workstation,omitempty"`
	Mountpoints []string `json:"mountpoints,omitempty"`
	Name *string `json:"name,omitempty"`
	Note *string `json:"note,omitempty"`
	PlannerSettings *ModelAPIPlannerSettings `json:"planner_settings,omitempty"`
	Provider *string `json:"provider,omitempty"`
	ProviderSettings map[string]interface{} `json:"provider_settings,omitempty"`
	Setup *string `json:"setup,omitempty"`
	SetupAsSudo *bool `json:"setup_as_sudo,omitempty"`
	SingleTaskDistro *bool `json:"single_task_distro,omitempty"`
	SshOptions []string `json:"ssh_options,omitempty"`
	User *string `json:"user,omitempty"`
	UserSpawnAllowed *bool `json:"user_spawn_allowed,omitempty"`
	ValidProjects []string `json:"valid_projects,omitempty"`
	WarningNote *string `json:"warning_note,omitempty"`
	WorkDir *string `json:"work_dir,omitempty"`
}

// NewModelAPIDistro instantiates a new ModelAPIDistro object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIDistro() *ModelAPIDistro {
	this := ModelAPIDistro{}
	return &this
}

// NewModelAPIDistroWithDefaults instantiates a new ModelAPIDistro object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIDistroWithDefaults() *ModelAPIDistro {
	this := ModelAPIDistro{}
	return &this
}

// GetAdminOnly returns the AdminOnly field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetAdminOnly() bool {
	if o == nil || IsNil(o.AdminOnly) {
		var ret bool
		return ret
	}
	return *o.AdminOnly
}

// GetAdminOnlyOk returns a tuple with the AdminOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetAdminOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.AdminOnly) {
		return nil, false
	}
	return o.AdminOnly, true
}

// HasAdminOnly returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasAdminOnly() bool {
	if o != nil && !IsNil(o.AdminOnly) {
		return true
	}

	return false
}

// SetAdminOnly gets a reference to the given bool and assigns it to the AdminOnly field.
func (o *ModelAPIDistro) SetAdminOnly(v bool) {
	o.AdminOnly = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *ModelAPIDistro) SetAliases(v []string) {
	o.Aliases = v
}

// GetArch returns the Arch field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetArch() string {
	if o == nil || IsNil(o.Arch) {
		var ret string
		return ret
	}
	return *o.Arch
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetArchOk() (*string, bool) {
	if o == nil || IsNil(o.Arch) {
		return nil, false
	}
	return o.Arch, true
}

// HasArch returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasArch() bool {
	if o != nil && !IsNil(o.Arch) {
		return true
	}

	return false
}

// SetArch gets a reference to the given string and assigns it to the Arch field.
func (o *ModelAPIDistro) SetArch(v string) {
	o.Arch = &v
}

// GetAuthorizedKeysFile returns the AuthorizedKeysFile field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetAuthorizedKeysFile() string {
	if o == nil || IsNil(o.AuthorizedKeysFile) {
		var ret string
		return ret
	}
	return *o.AuthorizedKeysFile
}

// GetAuthorizedKeysFileOk returns a tuple with the AuthorizedKeysFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetAuthorizedKeysFileOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizedKeysFile) {
		return nil, false
	}
	return o.AuthorizedKeysFile, true
}

// HasAuthorizedKeysFile returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasAuthorizedKeysFile() bool {
	if o != nil && !IsNil(o.AuthorizedKeysFile) {
		return true
	}

	return false
}

// SetAuthorizedKeysFile gets a reference to the given string and assigns it to the AuthorizedKeysFile field.
func (o *ModelAPIDistro) SetAuthorizedKeysFile(v string) {
	o.AuthorizedKeysFile = &v
}

// GetBootstrapSettings returns the BootstrapSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetBootstrapSettings() ModelAPIBootstrapSettings {
	if o == nil || IsNil(o.BootstrapSettings) {
		var ret ModelAPIBootstrapSettings
		return ret
	}
	return *o.BootstrapSettings
}

// GetBootstrapSettingsOk returns a tuple with the BootstrapSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetBootstrapSettingsOk() (*ModelAPIBootstrapSettings, bool) {
	if o == nil || IsNil(o.BootstrapSettings) {
		return nil, false
	}
	return o.BootstrapSettings, true
}

// HasBootstrapSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasBootstrapSettings() bool {
	if o != nil && !IsNil(o.BootstrapSettings) {
		return true
	}

	return false
}

// SetBootstrapSettings gets a reference to the given ModelAPIBootstrapSettings and assigns it to the BootstrapSettings field.
func (o *ModelAPIDistro) SetBootstrapSettings(v ModelAPIBootstrapSettings) {
	o.BootstrapSettings = &v
}

// GetContainerPool returns the ContainerPool field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetContainerPool() string {
	if o == nil || IsNil(o.ContainerPool) {
		var ret string
		return ret
	}
	return *o.ContainerPool
}

// GetContainerPoolOk returns a tuple with the ContainerPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetContainerPoolOk() (*string, bool) {
	if o == nil || IsNil(o.ContainerPool) {
		return nil, false
	}
	return o.ContainerPool, true
}

// HasContainerPool returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasContainerPool() bool {
	if o != nil && !IsNil(o.ContainerPool) {
		return true
	}

	return false
}

// SetContainerPool gets a reference to the given string and assigns it to the ContainerPool field.
func (o *ModelAPIDistro) SetContainerPool(v string) {
	o.ContainerPool = &v
}

// GetDisableShallowClone returns the DisableShallowClone field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetDisableShallowClone() bool {
	if o == nil || IsNil(o.DisableShallowClone) {
		var ret bool
		return ret
	}
	return *o.DisableShallowClone
}

// GetDisableShallowCloneOk returns a tuple with the DisableShallowClone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetDisableShallowCloneOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableShallowClone) {
		return nil, false
	}
	return o.DisableShallowClone, true
}

// HasDisableShallowClone returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasDisableShallowClone() bool {
	if o != nil && !IsNil(o.DisableShallowClone) {
		return true
	}

	return false
}

// SetDisableShallowClone gets a reference to the given bool and assigns it to the DisableShallowClone field.
func (o *ModelAPIDistro) SetDisableShallowClone(v bool) {
	o.DisableShallowClone = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *ModelAPIDistro) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetDispatcherSettings returns the DispatcherSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetDispatcherSettings() ModelAPIDispatcherSettings {
	if o == nil || IsNil(o.DispatcherSettings) {
		var ret ModelAPIDispatcherSettings
		return ret
	}
	return *o.DispatcherSettings
}

// GetDispatcherSettingsOk returns a tuple with the DispatcherSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetDispatcherSettingsOk() (*ModelAPIDispatcherSettings, bool) {
	if o == nil || IsNil(o.DispatcherSettings) {
		return nil, false
	}
	return o.DispatcherSettings, true
}

// HasDispatcherSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasDispatcherSettings() bool {
	if o != nil && !IsNil(o.DispatcherSettings) {
		return true
	}

	return false
}

// SetDispatcherSettings gets a reference to the given ModelAPIDispatcherSettings and assigns it to the DispatcherSettings field.
func (o *ModelAPIDistro) SetDispatcherSettings(v ModelAPIDispatcherSettings) {
	o.DispatcherSettings = &v
}

// GetExecUser returns the ExecUser field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetExecUser() string {
	if o == nil || IsNil(o.ExecUser) {
		var ret string
		return ret
	}
	return *o.ExecUser
}

// GetExecUserOk returns a tuple with the ExecUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetExecUserOk() (*string, bool) {
	if o == nil || IsNil(o.ExecUser) {
		return nil, false
	}
	return o.ExecUser, true
}

// HasExecUser returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasExecUser() bool {
	if o != nil && !IsNil(o.ExecUser) {
		return true
	}

	return false
}

// SetExecUser gets a reference to the given string and assigns it to the ExecUser field.
func (o *ModelAPIDistro) SetExecUser(v string) {
	o.ExecUser = &v
}

// GetExpansions returns the Expansions field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetExpansions() []ModelAPIExpansion {
	if o == nil || IsNil(o.Expansions) {
		var ret []ModelAPIExpansion
		return ret
	}
	return o.Expansions
}

// GetExpansionsOk returns a tuple with the Expansions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetExpansionsOk() ([]ModelAPIExpansion, bool) {
	if o == nil || IsNil(o.Expansions) {
		return nil, false
	}
	return o.Expansions, true
}

// HasExpansions returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasExpansions() bool {
	if o != nil && !IsNil(o.Expansions) {
		return true
	}

	return false
}

// SetExpansions gets a reference to the given []ModelAPIExpansion and assigns it to the Expansions field.
func (o *ModelAPIDistro) SetExpansions(v []ModelAPIExpansion) {
	o.Expansions = v
}

// GetFinderSettings returns the FinderSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetFinderSettings() ModelAPIFinderSettings {
	if o == nil || IsNil(o.FinderSettings) {
		var ret ModelAPIFinderSettings
		return ret
	}
	return *o.FinderSettings
}

// GetFinderSettingsOk returns a tuple with the FinderSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetFinderSettingsOk() (*ModelAPIFinderSettings, bool) {
	if o == nil || IsNil(o.FinderSettings) {
		return nil, false
	}
	return o.FinderSettings, true
}

// HasFinderSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasFinderSettings() bool {
	if o != nil && !IsNil(o.FinderSettings) {
		return true
	}

	return false
}

// SetFinderSettings gets a reference to the given ModelAPIFinderSettings and assigns it to the FinderSettings field.
func (o *ModelAPIDistro) SetFinderSettings(v ModelAPIFinderSettings) {
	o.FinderSettings = &v
}

// GetHomeVolumeSettings returns the HomeVolumeSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetHomeVolumeSettings() ModelAPIHomeVolumeSettings {
	if o == nil || IsNil(o.HomeVolumeSettings) {
		var ret ModelAPIHomeVolumeSettings
		return ret
	}
	return *o.HomeVolumeSettings
}

// GetHomeVolumeSettingsOk returns a tuple with the HomeVolumeSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetHomeVolumeSettingsOk() (*ModelAPIHomeVolumeSettings, bool) {
	if o == nil || IsNil(o.HomeVolumeSettings) {
		return nil, false
	}
	return o.HomeVolumeSettings, true
}

// HasHomeVolumeSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasHomeVolumeSettings() bool {
	if o != nil && !IsNil(o.HomeVolumeSettings) {
		return true
	}

	return false
}

// SetHomeVolumeSettings gets a reference to the given ModelAPIHomeVolumeSettings and assigns it to the HomeVolumeSettings field.
func (o *ModelAPIDistro) SetHomeVolumeSettings(v ModelAPIHomeVolumeSettings) {
	o.HomeVolumeSettings = &v
}

// GetHostAllocatorSettings returns the HostAllocatorSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetHostAllocatorSettings() ModelAPIHostAllocatorSettings {
	if o == nil || IsNil(o.HostAllocatorSettings) {
		var ret ModelAPIHostAllocatorSettings
		return ret
	}
	return *o.HostAllocatorSettings
}

// GetHostAllocatorSettingsOk returns a tuple with the HostAllocatorSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetHostAllocatorSettingsOk() (*ModelAPIHostAllocatorSettings, bool) {
	if o == nil || IsNil(o.HostAllocatorSettings) {
		return nil, false
	}
	return o.HostAllocatorSettings, true
}

// HasHostAllocatorSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasHostAllocatorSettings() bool {
	if o != nil && !IsNil(o.HostAllocatorSettings) {
		return true
	}

	return false
}

// SetHostAllocatorSettings gets a reference to the given ModelAPIHostAllocatorSettings and assigns it to the HostAllocatorSettings field.
func (o *ModelAPIDistro) SetHostAllocatorSettings(v ModelAPIHostAllocatorSettings) {
	o.HostAllocatorSettings = &v
}

// GetIcecreamSettings returns the IcecreamSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetIcecreamSettings() ModelAPIIceCreamSettings {
	if o == nil || IsNil(o.IcecreamSettings) {
		var ret ModelAPIIceCreamSettings
		return ret
	}
	return *o.IcecreamSettings
}

// GetIcecreamSettingsOk returns a tuple with the IcecreamSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetIcecreamSettingsOk() (*ModelAPIIceCreamSettings, bool) {
	if o == nil || IsNil(o.IcecreamSettings) {
		return nil, false
	}
	return o.IcecreamSettings, true
}

// HasIcecreamSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasIcecreamSettings() bool {
	if o != nil && !IsNil(o.IcecreamSettings) {
		return true
	}

	return false
}

// SetIcecreamSettings gets a reference to the given ModelAPIIceCreamSettings and assigns it to the IcecreamSettings field.
func (o *ModelAPIDistro) SetIcecreamSettings(v ModelAPIIceCreamSettings) {
	o.IcecreamSettings = &v
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetImageId() string {
	if o == nil || IsNil(o.ImageId) {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetImageIdOk() (*string, bool) {
	if o == nil || IsNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasImageId() bool {
	if o != nil && !IsNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *ModelAPIDistro) SetImageId(v string) {
	o.ImageId = &v
}

// GetIsCluster returns the IsCluster field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetIsCluster() bool {
	if o == nil || IsNil(o.IsCluster) {
		var ret bool
		return ret
	}
	return *o.IsCluster
}

// GetIsClusterOk returns a tuple with the IsCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetIsClusterOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCluster) {
		return nil, false
	}
	return o.IsCluster, true
}

// HasIsCluster returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasIsCluster() bool {
	if o != nil && !IsNil(o.IsCluster) {
		return true
	}

	return false
}

// SetIsCluster gets a reference to the given bool and assigns it to the IsCluster field.
func (o *ModelAPIDistro) SetIsCluster(v bool) {
	o.IsCluster = &v
}

// GetIsVirtualWorkstation returns the IsVirtualWorkstation field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetIsVirtualWorkstation() bool {
	if o == nil || IsNil(o.IsVirtualWorkstation) {
		var ret bool
		return ret
	}
	return *o.IsVirtualWorkstation
}

// GetIsVirtualWorkstationOk returns a tuple with the IsVirtualWorkstation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetIsVirtualWorkstationOk() (*bool, bool) {
	if o == nil || IsNil(o.IsVirtualWorkstation) {
		return nil, false
	}
	return o.IsVirtualWorkstation, true
}

// HasIsVirtualWorkstation returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasIsVirtualWorkstation() bool {
	if o != nil && !IsNil(o.IsVirtualWorkstation) {
		return true
	}

	return false
}

// SetIsVirtualWorkstation gets a reference to the given bool and assigns it to the IsVirtualWorkstation field.
func (o *ModelAPIDistro) SetIsVirtualWorkstation(v bool) {
	o.IsVirtualWorkstation = &v
}

// GetMountpoints returns the Mountpoints field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetMountpoints() []string {
	if o == nil || IsNil(o.Mountpoints) {
		var ret []string
		return ret
	}
	return o.Mountpoints
}

// GetMountpointsOk returns a tuple with the Mountpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetMountpointsOk() ([]string, bool) {
	if o == nil || IsNil(o.Mountpoints) {
		return nil, false
	}
	return o.Mountpoints, true
}

// HasMountpoints returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasMountpoints() bool {
	if o != nil && !IsNil(o.Mountpoints) {
		return true
	}

	return false
}

// SetMountpoints gets a reference to the given []string and assigns it to the Mountpoints field.
func (o *ModelAPIDistro) SetMountpoints(v []string) {
	o.Mountpoints = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModelAPIDistro) SetName(v string) {
	o.Name = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *ModelAPIDistro) SetNote(v string) {
	o.Note = &v
}

// GetPlannerSettings returns the PlannerSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetPlannerSettings() ModelAPIPlannerSettings {
	if o == nil || IsNil(o.PlannerSettings) {
		var ret ModelAPIPlannerSettings
		return ret
	}
	return *o.PlannerSettings
}

// GetPlannerSettingsOk returns a tuple with the PlannerSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetPlannerSettingsOk() (*ModelAPIPlannerSettings, bool) {
	if o == nil || IsNil(o.PlannerSettings) {
		return nil, false
	}
	return o.PlannerSettings, true
}

// HasPlannerSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasPlannerSettings() bool {
	if o != nil && !IsNil(o.PlannerSettings) {
		return true
	}

	return false
}

// SetPlannerSettings gets a reference to the given ModelAPIPlannerSettings and assigns it to the PlannerSettings field.
func (o *ModelAPIDistro) SetPlannerSettings(v ModelAPIPlannerSettings) {
	o.PlannerSettings = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *ModelAPIDistro) SetProvider(v string) {
	o.Provider = &v
}

// GetProviderSettings returns the ProviderSettings field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetProviderSettings() map[string]interface{} {
	if o == nil || IsNil(o.ProviderSettings) {
		var ret map[string]interface{}
		return ret
	}
	return o.ProviderSettings
}

// GetProviderSettingsOk returns a tuple with the ProviderSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetProviderSettingsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ProviderSettings) {
		return map[string]interface{}{}, false
	}
	return o.ProviderSettings, true
}

// HasProviderSettings returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasProviderSettings() bool {
	if o != nil && !IsNil(o.ProviderSettings) {
		return true
	}

	return false
}

// SetProviderSettings gets a reference to the given map[string]interface{} and assigns it to the ProviderSettings field.
func (o *ModelAPIDistro) SetProviderSettings(v map[string]interface{}) {
	o.ProviderSettings = v
}

// GetSetup returns the Setup field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetSetup() string {
	if o == nil || IsNil(o.Setup) {
		var ret string
		return ret
	}
	return *o.Setup
}

// GetSetupOk returns a tuple with the Setup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetSetupOk() (*string, bool) {
	if o == nil || IsNil(o.Setup) {
		return nil, false
	}
	return o.Setup, true
}

// HasSetup returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasSetup() bool {
	if o != nil && !IsNil(o.Setup) {
		return true
	}

	return false
}

// SetSetup gets a reference to the given string and assigns it to the Setup field.
func (o *ModelAPIDistro) SetSetup(v string) {
	o.Setup = &v
}

// GetSetupAsSudo returns the SetupAsSudo field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetSetupAsSudo() bool {
	if o == nil || IsNil(o.SetupAsSudo) {
		var ret bool
		return ret
	}
	return *o.SetupAsSudo
}

// GetSetupAsSudoOk returns a tuple with the SetupAsSudo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetSetupAsSudoOk() (*bool, bool) {
	if o == nil || IsNil(o.SetupAsSudo) {
		return nil, false
	}
	return o.SetupAsSudo, true
}

// HasSetupAsSudo returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasSetupAsSudo() bool {
	if o != nil && !IsNil(o.SetupAsSudo) {
		return true
	}

	return false
}

// SetSetupAsSudo gets a reference to the given bool and assigns it to the SetupAsSudo field.
func (o *ModelAPIDistro) SetSetupAsSudo(v bool) {
	o.SetupAsSudo = &v
}

// GetSingleTaskDistro returns the SingleTaskDistro field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetSingleTaskDistro() bool {
	if o == nil || IsNil(o.SingleTaskDistro) {
		var ret bool
		return ret
	}
	return *o.SingleTaskDistro
}

// GetSingleTaskDistroOk returns a tuple with the SingleTaskDistro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetSingleTaskDistroOk() (*bool, bool) {
	if o == nil || IsNil(o.SingleTaskDistro) {
		return nil, false
	}
	return o.SingleTaskDistro, true
}

// HasSingleTaskDistro returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasSingleTaskDistro() bool {
	if o != nil && !IsNil(o.SingleTaskDistro) {
		return true
	}

	return false
}

// SetSingleTaskDistro gets a reference to the given bool and assigns it to the SingleTaskDistro field.
func (o *ModelAPIDistro) SetSingleTaskDistro(v bool) {
	o.SingleTaskDistro = &v
}

// GetSshOptions returns the SshOptions field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetSshOptions() []string {
	if o == nil || IsNil(o.SshOptions) {
		var ret []string
		return ret
	}
	return o.SshOptions
}

// GetSshOptionsOk returns a tuple with the SshOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetSshOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.SshOptions) {
		return nil, false
	}
	return o.SshOptions, true
}

// HasSshOptions returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasSshOptions() bool {
	if o != nil && !IsNil(o.SshOptions) {
		return true
	}

	return false
}

// SetSshOptions gets a reference to the given []string and assigns it to the SshOptions field.
func (o *ModelAPIDistro) SetSshOptions(v []string) {
	o.SshOptions = v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *ModelAPIDistro) SetUser(v string) {
	o.User = &v
}

// GetUserSpawnAllowed returns the UserSpawnAllowed field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetUserSpawnAllowed() bool {
	if o == nil || IsNil(o.UserSpawnAllowed) {
		var ret bool
		return ret
	}
	return *o.UserSpawnAllowed
}

// GetUserSpawnAllowedOk returns a tuple with the UserSpawnAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetUserSpawnAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.UserSpawnAllowed) {
		return nil, false
	}
	return o.UserSpawnAllowed, true
}

// HasUserSpawnAllowed returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasUserSpawnAllowed() bool {
	if o != nil && !IsNil(o.UserSpawnAllowed) {
		return true
	}

	return false
}

// SetUserSpawnAllowed gets a reference to the given bool and assigns it to the UserSpawnAllowed field.
func (o *ModelAPIDistro) SetUserSpawnAllowed(v bool) {
	o.UserSpawnAllowed = &v
}

// GetValidProjects returns the ValidProjects field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetValidProjects() []string {
	if o == nil || IsNil(o.ValidProjects) {
		var ret []string
		return ret
	}
	return o.ValidProjects
}

// GetValidProjectsOk returns a tuple with the ValidProjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetValidProjectsOk() ([]string, bool) {
	if o == nil || IsNil(o.ValidProjects) {
		return nil, false
	}
	return o.ValidProjects, true
}

// HasValidProjects returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasValidProjects() bool {
	if o != nil && !IsNil(o.ValidProjects) {
		return true
	}

	return false
}

// SetValidProjects gets a reference to the given []string and assigns it to the ValidProjects field.
func (o *ModelAPIDistro) SetValidProjects(v []string) {
	o.ValidProjects = v
}

// GetWarningNote returns the WarningNote field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetWarningNote() string {
	if o == nil || IsNil(o.WarningNote) {
		var ret string
		return ret
	}
	return *o.WarningNote
}

// GetWarningNoteOk returns a tuple with the WarningNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetWarningNoteOk() (*string, bool) {
	if o == nil || IsNil(o.WarningNote) {
		return nil, false
	}
	return o.WarningNote, true
}

// HasWarningNote returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasWarningNote() bool {
	if o != nil && !IsNil(o.WarningNote) {
		return true
	}

	return false
}

// SetWarningNote gets a reference to the given string and assigns it to the WarningNote field.
func (o *ModelAPIDistro) SetWarningNote(v string) {
	o.WarningNote = &v
}

// GetWorkDir returns the WorkDir field value if set, zero value otherwise.
func (o *ModelAPIDistro) GetWorkDir() string {
	if o == nil || IsNil(o.WorkDir) {
		var ret string
		return ret
	}
	return *o.WorkDir
}

// GetWorkDirOk returns a tuple with the WorkDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDistro) GetWorkDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkDir) {
		return nil, false
	}
	return o.WorkDir, true
}

// HasWorkDir returns a boolean if a field has been set.
func (o *ModelAPIDistro) HasWorkDir() bool {
	if o != nil && !IsNil(o.WorkDir) {
		return true
	}

	return false
}

// SetWorkDir gets a reference to the given string and assigns it to the WorkDir field.
func (o *ModelAPIDistro) SetWorkDir(v string) {
	o.WorkDir = &v
}

func (o ModelAPIDistro) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIDistro) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdminOnly) {
		toSerialize["admin_only"] = o.AdminOnly
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.Arch) {
		toSerialize["arch"] = o.Arch
	}
	if !IsNil(o.AuthorizedKeysFile) {
		toSerialize["authorized_keys_file"] = o.AuthorizedKeysFile
	}
	if !IsNil(o.BootstrapSettings) {
		toSerialize["bootstrap_settings"] = o.BootstrapSettings
	}
	if !IsNil(o.ContainerPool) {
		toSerialize["container_pool"] = o.ContainerPool
	}
	if !IsNil(o.DisableShallowClone) {
		toSerialize["disable_shallow_clone"] = o.DisableShallowClone
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if !IsNil(o.DispatcherSettings) {
		toSerialize["dispatcher_settings"] = o.DispatcherSettings
	}
	if !IsNil(o.ExecUser) {
		toSerialize["exec_user"] = o.ExecUser
	}
	if !IsNil(o.Expansions) {
		toSerialize["expansions"] = o.Expansions
	}
	if !IsNil(o.FinderSettings) {
		toSerialize["finder_settings"] = o.FinderSettings
	}
	if !IsNil(o.HomeVolumeSettings) {
		toSerialize["home_volume_settings"] = o.HomeVolumeSettings
	}
	if !IsNil(o.HostAllocatorSettings) {
		toSerialize["host_allocator_settings"] = o.HostAllocatorSettings
	}
	if !IsNil(o.IcecreamSettings) {
		toSerialize["icecream_settings"] = o.IcecreamSettings
	}
	if !IsNil(o.ImageId) {
		toSerialize["image_id"] = o.ImageId
	}
	if !IsNil(o.IsCluster) {
		toSerialize["is_cluster"] = o.IsCluster
	}
	if !IsNil(o.IsVirtualWorkstation) {
		toSerialize["is_virtual_workstation"] = o.IsVirtualWorkstation
	}
	if !IsNil(o.Mountpoints) {
		toSerialize["mountpoints"] = o.Mountpoints
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.PlannerSettings) {
		toSerialize["planner_settings"] = o.PlannerSettings
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.ProviderSettings) {
		toSerialize["provider_settings"] = o.ProviderSettings
	}
	if !IsNil(o.Setup) {
		toSerialize["setup"] = o.Setup
	}
	if !IsNil(o.SetupAsSudo) {
		toSerialize["setup_as_sudo"] = o.SetupAsSudo
	}
	if !IsNil(o.SingleTaskDistro) {
		toSerialize["single_task_distro"] = o.SingleTaskDistro
	}
	if !IsNil(o.SshOptions) {
		toSerialize["ssh_options"] = o.SshOptions
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.UserSpawnAllowed) {
		toSerialize["user_spawn_allowed"] = o.UserSpawnAllowed
	}
	if !IsNil(o.ValidProjects) {
		toSerialize["valid_projects"] = o.ValidProjects
	}
	if !IsNil(o.WarningNote) {
		toSerialize["warning_note"] = o.WarningNote
	}
	if !IsNil(o.WorkDir) {
		toSerialize["work_dir"] = o.WorkDir
	}
	return toSerialize, nil
}

type NullableModelAPIDistro struct {
	value *ModelAPIDistro
	isSet bool
}

func (v NullableModelAPIDistro) Get() *ModelAPIDistro {
	return v.value
}

func (v *NullableModelAPIDistro) Set(val *ModelAPIDistro) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIDistro) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIDistro) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIDistro(val *ModelAPIDistro) *NullableModelAPIDistro {
	return &NullableModelAPIDistro{value: val, isSet: true}
}

func (v NullableModelAPIDistro) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIDistro) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


