/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIProjectBanner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIProjectBanner{}

// ModelAPIProjectBanner struct for ModelAPIProjectBanner
type ModelAPIProjectBanner struct {
	// Banner text.
	Text *string `json:"text,omitempty"`
	// Banner theme.
	Theme *EvergreenBannerTheme `json:"theme,omitempty"`
}

// NewModelAPIProjectBanner instantiates a new ModelAPIProjectBanner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIProjectBanner() *ModelAPIProjectBanner {
	this := ModelAPIProjectBanner{}
	return &this
}

// NewModelAPIProjectBannerWithDefaults instantiates a new ModelAPIProjectBanner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIProjectBannerWithDefaults() *ModelAPIProjectBanner {
	this := ModelAPIProjectBanner{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *ModelAPIProjectBanner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIProjectBanner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *ModelAPIProjectBanner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *ModelAPIProjectBanner) SetText(v string) {
	o.Text = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise.
func (o *ModelAPIProjectBanner) GetTheme() EvergreenBannerTheme {
	if o == nil || IsNil(o.Theme) {
		var ret EvergreenBannerTheme
		return ret
	}
	return *o.Theme
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIProjectBanner) GetThemeOk() (*EvergreenBannerTheme, bool) {
	if o == nil || IsNil(o.Theme) {
		return nil, false
	}
	return o.Theme, true
}

// HasTheme returns a boolean if a field has been set.
func (o *ModelAPIProjectBanner) HasTheme() bool {
	if o != nil && !IsNil(o.Theme) {
		return true
	}

	return false
}

// SetTheme gets a reference to the given EvergreenBannerTheme and assigns it to the Theme field.
func (o *ModelAPIProjectBanner) SetTheme(v EvergreenBannerTheme) {
	o.Theme = &v
}

func (o ModelAPIProjectBanner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIProjectBanner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Theme) {
		toSerialize["theme"] = o.Theme
	}
	return toSerialize, nil
}

type NullableModelAPIProjectBanner struct {
	value *ModelAPIProjectBanner
	isSet bool
}

func (v NullableModelAPIProjectBanner) Get() *ModelAPIProjectBanner {
	return v.value
}

func (v *NullableModelAPIProjectBanner) Set(val *ModelAPIProjectBanner) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIProjectBanner) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIProjectBanner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIProjectBanner(val *ModelAPIProjectBanner) *NullableModelAPIProjectBanner {
	return &NullableModelAPIProjectBanner{value: val, isSet: true}
}

func (v NullableModelAPIProjectBanner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIProjectBanner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


