/*
Test Selection Services

Test Selection services, owner: DevProd Services & Integrations team

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost{}

// BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost struct for BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost
type BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost struct {
	ProjectId string `json:"project_id"`
}

type _BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost

// NewBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost instantiates a new BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost(projectId string) *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost {
	this := BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost{}
	this.ProjectId = projectId
	return &this
}

// NewBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPostWithDefaults instantiates a new BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPostWithDefaults() *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost {
	this := BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) SetProjectId(v string) {
	o.ProjectId = v
}

func (o BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	return toSerialize, nil
}

func (o *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost := _BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost)

	if err != nil {
		return err
	}

	*o = BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost(varBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost)

	return err
}

type NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost struct {
	value *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost
	isSet bool
}

func (v NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) Get() *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost {
	return v.value
}

func (v *NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) Set(val *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost(val *BodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) *NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost {
	return &NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost{value: val, isSet: true}
}

func (v NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyGetProjectQuarantinedDataInBodyApiTestSelectionGetProjectQuarantinedPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


