/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelAPIDependency type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelAPIDependency{}

// ModelAPIDependency struct for ModelAPIDependency
type ModelAPIDependency struct {
	Id *string `json:"id,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewModelAPIDependency instantiates a new ModelAPIDependency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelAPIDependency() *ModelAPIDependency {
	this := ModelAPIDependency{}
	return &this
}

// NewModelAPIDependencyWithDefaults instantiates a new ModelAPIDependency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelAPIDependencyWithDefaults() *ModelAPIDependency {
	this := ModelAPIDependency{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelAPIDependency) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDependency) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelAPIDependency) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModelAPIDependency) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ModelAPIDependency) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelAPIDependency) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ModelAPIDependency) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ModelAPIDependency) SetStatus(v string) {
	o.Status = &v
}

func (o ModelAPIDependency) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelAPIDependency) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableModelAPIDependency struct {
	value *ModelAPIDependency
	isSet bool
}

func (v NullableModelAPIDependency) Get() *ModelAPIDependency {
	return v.value
}

func (v *NullableModelAPIDependency) Set(val *ModelAPIDependency) {
	v.value = val
	v.isSet = true
}

func (v NullableModelAPIDependency) IsSet() bool {
	return v.isSet
}

func (v *NullableModelAPIDependency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelAPIDependency(val *ModelAPIDependency) *NullableModelAPIDependency {
	return &NullableModelAPIDependency{value: val, isSet: true}
}

func (v NullableModelAPIDependency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelAPIDependency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


