/*
Evergreen REST v2 API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ModelLogLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelLogLinks{}

// ModelLogLinks struct for ModelLogLinks
type ModelLogLinks struct {
	// Link to logs created by the agent process
	AgentLog *string `json:"agent_log,omitempty"`
	// Link to logs containing merged copy of all other logs
	AllLog *string `json:"all_log,omitempty"`
	EventLog *string `json:"event_log,omitempty"`
	// Link to logs created by the machine running the task
	SystemLog *string `json:"system_log,omitempty"`
	// Link to logs created by the task execution
	TaskLog *string `json:"task_log,omitempty"`
}

// NewModelLogLinks instantiates a new ModelLogLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelLogLinks() *ModelLogLinks {
	this := ModelLogLinks{}
	return &this
}

// NewModelLogLinksWithDefaults instantiates a new ModelLogLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelLogLinksWithDefaults() *ModelLogLinks {
	this := ModelLogLinks{}
	return &this
}

// GetAgentLog returns the AgentLog field value if set, zero value otherwise.
func (o *ModelLogLinks) GetAgentLog() string {
	if o == nil || IsNil(o.AgentLog) {
		var ret string
		return ret
	}
	return *o.AgentLog
}

// GetAgentLogOk returns a tuple with the AgentLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLogLinks) GetAgentLogOk() (*string, bool) {
	if o == nil || IsNil(o.AgentLog) {
		return nil, false
	}
	return o.AgentLog, true
}

// HasAgentLog returns a boolean if a field has been set.
func (o *ModelLogLinks) HasAgentLog() bool {
	if o != nil && !IsNil(o.AgentLog) {
		return true
	}

	return false
}

// SetAgentLog gets a reference to the given string and assigns it to the AgentLog field.
func (o *ModelLogLinks) SetAgentLog(v string) {
	o.AgentLog = &v
}

// GetAllLog returns the AllLog field value if set, zero value otherwise.
func (o *ModelLogLinks) GetAllLog() string {
	if o == nil || IsNil(o.AllLog) {
		var ret string
		return ret
	}
	return *o.AllLog
}

// GetAllLogOk returns a tuple with the AllLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLogLinks) GetAllLogOk() (*string, bool) {
	if o == nil || IsNil(o.AllLog) {
		return nil, false
	}
	return o.AllLog, true
}

// HasAllLog returns a boolean if a field has been set.
func (o *ModelLogLinks) HasAllLog() bool {
	if o != nil && !IsNil(o.AllLog) {
		return true
	}

	return false
}

// SetAllLog gets a reference to the given string and assigns it to the AllLog field.
func (o *ModelLogLinks) SetAllLog(v string) {
	o.AllLog = &v
}

// GetEventLog returns the EventLog field value if set, zero value otherwise.
func (o *ModelLogLinks) GetEventLog() string {
	if o == nil || IsNil(o.EventLog) {
		var ret string
		return ret
	}
	return *o.EventLog
}

// GetEventLogOk returns a tuple with the EventLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLogLinks) GetEventLogOk() (*string, bool) {
	if o == nil || IsNil(o.EventLog) {
		return nil, false
	}
	return o.EventLog, true
}

// HasEventLog returns a boolean if a field has been set.
func (o *ModelLogLinks) HasEventLog() bool {
	if o != nil && !IsNil(o.EventLog) {
		return true
	}

	return false
}

// SetEventLog gets a reference to the given string and assigns it to the EventLog field.
func (o *ModelLogLinks) SetEventLog(v string) {
	o.EventLog = &v
}

// GetSystemLog returns the SystemLog field value if set, zero value otherwise.
func (o *ModelLogLinks) GetSystemLog() string {
	if o == nil || IsNil(o.SystemLog) {
		var ret string
		return ret
	}
	return *o.SystemLog
}

// GetSystemLogOk returns a tuple with the SystemLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLogLinks) GetSystemLogOk() (*string, bool) {
	if o == nil || IsNil(o.SystemLog) {
		return nil, false
	}
	return o.SystemLog, true
}

// HasSystemLog returns a boolean if a field has been set.
func (o *ModelLogLinks) HasSystemLog() bool {
	if o != nil && !IsNil(o.SystemLog) {
		return true
	}

	return false
}

// SetSystemLog gets a reference to the given string and assigns it to the SystemLog field.
func (o *ModelLogLinks) SetSystemLog(v string) {
	o.SystemLog = &v
}

// GetTaskLog returns the TaskLog field value if set, zero value otherwise.
func (o *ModelLogLinks) GetTaskLog() string {
	if o == nil || IsNil(o.TaskLog) {
		var ret string
		return ret
	}
	return *o.TaskLog
}

// GetTaskLogOk returns a tuple with the TaskLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelLogLinks) GetTaskLogOk() (*string, bool) {
	if o == nil || IsNil(o.TaskLog) {
		return nil, false
	}
	return o.TaskLog, true
}

// HasTaskLog returns a boolean if a field has been set.
func (o *ModelLogLinks) HasTaskLog() bool {
	if o != nil && !IsNil(o.TaskLog) {
		return true
	}

	return false
}

// SetTaskLog gets a reference to the given string and assigns it to the TaskLog field.
func (o *ModelLogLinks) SetTaskLog(v string) {
	o.TaskLog = &v
}

func (o ModelLogLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelLogLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentLog) {
		toSerialize["agent_log"] = o.AgentLog
	}
	if !IsNil(o.AllLog) {
		toSerialize["all_log"] = o.AllLog
	}
	if !IsNil(o.EventLog) {
		toSerialize["event_log"] = o.EventLog
	}
	if !IsNil(o.SystemLog) {
		toSerialize["system_log"] = o.SystemLog
	}
	if !IsNil(o.TaskLog) {
		toSerialize["task_log"] = o.TaskLog
	}
	return toSerialize, nil
}

type NullableModelLogLinks struct {
	value *ModelLogLinks
	isSet bool
}

func (v NullableModelLogLinks) Get() *ModelLogLinks {
	return v.value
}

func (v *NullableModelLogLinks) Set(val *ModelLogLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableModelLogLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableModelLogLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelLogLinks(val *ModelLogLinks) *NullableModelLogLinks {
	return &NullableModelLogLinks{value: val, isSet: true}
}

func (v NullableModelLogLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelLogLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


