openapi: 3.1.0
info:
  description: "Test Selection services, owner: DevProd Services & Integrations team"
  title: Test Selection Services
  version: 1.0.0
servers:
- url: /
paths:
  /api/test_selection/select_tests/{project_id}/{requester}/{build_variant_name}/{task_id}/{task_name}/{test_names}/:
    get:
      description: |-
        Get the results of the default strategy.
        :param project_id: The project id.
        :param requester: The requester.
        :param build_variant_name: The build variant name.
        :param task_id: The task id.
        :param task_name: The task name.
        :param test_names: The test names.
        :param strategies: The set of strategies to use
        :return: A mapping from {Build variant x task x test} to a
                 true/false value indicating if the test should run
      operationId: select_tests_api_test_selection_select_tests__project_id___requester___build_variant_name___task_id___task_name___test_names___get
      parameters:
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: string
        style: simple
      - explode: false
        in: path
        name: requester
        required: true
        schema:
          title: Requester
          type: string
        style: simple
      - explode: false
        in: path
        name: build_variant_name
        required: true
        schema:
          title: Build Variant Name
          type: string
        style: simple
      - explode: false
        in: path
        name: task_id
        required: true
        schema:
          title: Task Id
          type: string
        style: simple
      - explode: false
        in: path
        name: task_name
        required: true
        schema:
          title: Task Name
          type: string
        style: simple
      - explode: false
        in: path
        name: test_names
        required: true
        schema:
          title: Test Names
          type: string
        style: simple
      - explode: true
        in: query
        name: strategies
        required: false
        schema:
          $ref: '#/components/schemas/StrategyEnum'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                uniqueItems: true
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Select Tests
      tags:
      - test_selection
  /api/test_selection/explain_tests/{project_id}/{requester}/{build_variant_name}/{task_id}/{task_name}/{test_names}/:
    get:
      description: |-
        Get the results of the default strategy as well as the explanation.
        :param project_id: The project id.
        :param requester: The requester.
        :param build_variant_name: The build variant name.
        :param task_id: The task id.
        :param task_name: The task name.
        :param test_names: The test names.
        :param strategies: The set of strategies to use
        :return: A mapping from {Build variant x task x test} to a
                 true/false value indicating if the test should run
      operationId: explain_select_tests_api_test_selection_explain_tests__project_id___requester___build_variant_name___task_id___task_name___test_names___get
      parameters:
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: string
        style: simple
      - explode: false
        in: path
        name: requester
        required: true
        schema:
          title: Requester
          type: string
        style: simple
      - explode: false
        in: path
        name: build_variant_name
        required: true
        schema:
          title: Build Variant Name
          type: string
        style: simple
      - explode: false
        in: path
        name: task_id
        required: true
        schema:
          title: Task Id
          type: string
        style: simple
      - explode: false
        in: path
        name: task_name
        required: true
        schema:
          title: Task Name
          type: string
        style: simple
      - explode: false
        in: path
        name: test_names
        required: true
        schema:
          title: Test Names
          type: string
        style: simple
      - explode: true
        in: query
        name: strategies
        required: false
        schema:
          $ref: '#/components/schemas/StrategyEnum'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Explanation'
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Explain Select Tests
      tags:
      - test_selection
components:
  schemas:
    Explanation:
      description: Explanation of the results.
      example:
        explanation: explanation
        test_name: test_name
        selected: true
      properties:
        test_name:
          title: Test Name
          type: string
        selected:
          title: Selected
          type: boolean
        explanation:
          title: Explanation
          type: string
      required:
      - explanation
      - selected
      - test_name
      title: Explanation
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    StrategyEnum:
      enum:
      - Optimistic
      title: StrategyEnum
      type: string
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
