openapi: 3.1.0
info:
  description: "Test Selection services, owner: DevProd Services & Integrations team"
  title: Test Selection Services
  version: 1.0.0
servers:
- url: /
paths:
  /api/test_selection/select_tests/{project_id}/{requester}/{build_variant_name}/{task_id}/{task_name}/:
    post:
      description: |-
        Get the results of the default strategy.
        :param project_id: The project id.
        :param requester: The requester.
        :param build_variant_name: The build variant name.
        :param task_id: The task id.
        :param task_name: The task name.
        :param test_names: The test names.
        :param strategies: The set of strategies to use
        :return: A mapping from {Build variant x task x test} to a
                 true/false value indicating if the test should run
      operationId: select_tests_api_test_selection_select_tests__project_id___requester___build_variant_name___task_id___task_name___post
      parameters:
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: string
        style: simple
      - explode: false
        in: path
        name: requester
        required: true
        schema:
          title: Requester
          type: string
        style: simple
      - explode: false
        in: path
        name: build_variant_name
        required: true
        schema:
          title: Build Variant Name
          type: string
        style: simple
      - explode: false
        in: path
        name: task_id
        required: true
        schema:
          title: Task Id
          type: string
        style: simple
      - explode: false
        in: path
        name: task_name
        required: true
        schema:
          title: Task Name
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_select_tests_api_test_selection_select_tests__project_id___requester___build_variant_name___task_id___task_name___post'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
                uniqueItems: true
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Select Tests
      tags:
      - test_selection
  /api/test_selection/explain_tests/{project_id}/{requester}/{build_variant_name}/{task_id}/{task_name}/:
    post:
      description: |-
        Get the results of the default strategy as well as the explanation.
        :param project_id: The project id.
        :param requester: The requester.
        :param build_variant_name: The build variant name.
        :param task_id: The task id.
        :param task_name: The task name.
        :param test_names: The test names.
        :param strategies: The set of strategies to use
        :return: A mapping from {Build variant x task x test} to a
                 true/false value indicating if the test should run
      operationId: explain_select_tests_api_test_selection_explain_tests__project_id___requester___build_variant_name___task_id___task_name___post
      parameters:
      - explode: false
        in: path
        name: project_id
        required: true
        schema:
          title: Project Id
          type: string
        style: simple
      - explode: false
        in: path
        name: requester
        required: true
        schema:
          title: Requester
          type: string
        style: simple
      - explode: false
        in: path
        name: build_variant_name
        required: true
        schema:
          title: Build Variant Name
          type: string
        style: simple
      - explode: false
        in: path
        name: task_id
        required: true
        schema:
          title: Task Id
          type: string
        style: simple
      - explode: false
        in: path
        name: task_name
        required: true
        schema:
          title: Task Name
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_explain_select_tests_api_test_selection_explain_tests__project_id___requester___build_variant_name___task_id___task_name___post'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Explanation'
                type: array
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Explain Select Tests
      tags:
      - test_selection
  /api/test_selection/explain_patch/{patch_id}/:
    post:
      description: |-
        Get the results of the default strategy as well as the explanation.
        :param patch_id: The patch id to compare results to.
        :param strategies: The set of strategies to use
        :return: A mapping from {Build variant x task x test} to a
                 true/false value indicating if the test should run
      operationId: explain_patch_api_test_selection_explain_patch__patch_id___post
      parameters:
      - explode: false
        in: path
        name: patch_id
        required: true
        schema:
          title: Patch Id
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              default:
              - Optimistic
              items:
                $ref: '#/components/schemas/StrategyEnum'
              type: array
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchExplanation'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Explain Patch
      tags:
      - test_selection
components:
  schemas:
    ? Body_explain_select_tests_api_test_selection_explain_tests__project_id___requester___build_variant_name___task_id___task_name___post
    : properties:
        test_names:
          items:
            type: string
          type: array
        strategies:
          default:
          - Optimistic
          items:
            $ref: '#/components/schemas/StrategyEnum'
          type: array
      required:
      - test_names
      title: Body_explain_select_tests_api_test_selection_explain_tests__project_id___requester___build_variant_name___task_id___task_name___post
    Body_select_tests_api_test_selection_select_tests__project_id___requester___build_variant_name___task_id___task_name___post:
      properties:
        test_names:
          items:
            type: string
          type: array
        strategies:
          default:
          - Optimistic
          items:
            $ref: '#/components/schemas/StrategyEnum'
          type: array
      required:
      - test_names
      title: Body_select_tests_api_test_selection_select_tests__project_id___requester___build_variant_name___task_id___task_name___post
    BuildExplanation:
      description: Explanation of the results of a single build variant
      example:
        build_variant: build_variant
        tasks:
          key:
            task_name: task_name
            tests:
              key:
                explanation: explanation
                test_name: test_name
                selected: true
                expected_outcome: success
      properties:
        build_variant:
          description: Build variant name (not display name)
          title: Build Variant
          type: string
        tasks:
          additionalProperties:
            $ref: '#/components/schemas/TaskExplanation'
          default: {}
          title: Tasks
      required:
      - build_variant
      title: BuildExplanation
    ExpectedOutcome:
      description: The expected outcome of a test for the selected strategy
      enum:
      - success
      - failure
      - unknown
      title: ExpectedOutcome
      type: string
    Explanation:
      description: Explanation of the results of a single test.
      example:
        explanation: explanation
        test_name: test_name
        selected: true
        expected_outcome: success
      properties:
        test_name:
          title: Test Name
          type: string
        selected:
          title: Selected
          type: boolean
        expected_outcome:
          $ref: '#/components/schemas/ExpectedOutcome'
        explanation:
          title: Explanation
          type: string
      required:
      - expected_outcome
      - explanation
      - selected
      - test_name
      title: Explanation
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    PatchExplanation:
      description: |-
        Explanation of the results of a whole patch

        The builds are mapped by build variant name (not display name)
      example:
        patch_id: patch_id
        builds:
          key:
            build_variant: build_variant
            tasks:
              key:
                task_name: task_name
                tests:
                  key:
                    explanation: explanation
                    test_name: test_name
                    selected: true
                    expected_outcome: success
      properties:
        patch_id:
          title: Patch Id
          type: string
        builds:
          additionalProperties:
            $ref: '#/components/schemas/BuildExplanation'
          default: {}
          title: Builds
      required:
      - patch_id
      title: PatchExplanation
    StrategyEnum:
      enum:
      - Optimistic
      - StartsWithT
      title: StrategyEnum
      type: string
    TaskExplanation:
      description: Explanation of the results of a single task.
      example:
        task_name: task_name
        tests:
          key:
            explanation: explanation
            test_name: test_name
            selected: true
            expected_outcome: success
      properties:
        task_name:
          title: Task Name
          type: string
        tests:
          additionalProperties:
            $ref: '#/components/schemas/Explanation'
          default: {}
          title: Tests
      required:
      - task_name
      title: TaskExplanation
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
